// Kappa dense notation parser. Generated by Kappa parser generator. Do not edit.
package dev.kappa;

import java.util.*;

public class KappaParser {

    // ── Token ──

    public enum TokenType {
        Ident,
        Number,
        String,
        LBrace,
        RBrace,
        LParen,
        RParen,
        LBracket,
        RBracket,
        Colon,
        Comma,
        Pipe,
        Star,
        Question,
        Bang,
        Tilde,
        At,
        Caret,
        Hash,
        PlusPlus,
        Equals,
        EOF
    }

    public record Token(TokenType type, String value, int line, int column, int offset) {}

    // ── AST ──

    public sealed interface FieldType permits PrimitiveType, ArrayType, ReferenceType, EnumType {}
    public record PrimitiveType(String code) implements FieldType {}
    public record ArrayType(FieldType elementType) implements FieldType {}
    public record ReferenceType(String entity) implements FieldType {}
    public record EnumType(List<String> values) implements FieldType {}

    public record Constraint(Double min, Double max) {}

    public record Field(
        String name, FieldType type,
        boolean required, boolean optional, boolean immutable,
        boolean indexed, boolean unique, boolean autoIncrement,
        boolean hidden, String format,
        Constraint constraint, Object defaultValue
    ) {}

    public record EnumDeclaration(String name, List<String> values) {}
    public record Entity(String name, List<Field> fields, List<List<String>> uniqueConstraints) {}
    public record Diagnostic(String message, int line, int column, int offset) {}
    public record KappaFile(List<Entity> entities, List<EnumDeclaration> enumDeclarations, List<Diagnostic> diagnostics) {}

    private static final Set<String> TYPE_CODES = Set.of("s", "t", "i", "f", "m", "b", "d", "dt", "id", "x");

    // ── Lexer ──

    private static class Lexer {
        private final String src;
        private int pos = 0, line = 1, col = 1;
        private Token peeked = null;

        Lexer(String source) { this.src = source; }

        Token peek() { if (peeked == null) peeked = scan(); return peeked; }

        Token next() {
            if (peeked != null) { var t = peeked; peeked = null; return t; }
            return scan();
        }

        boolean check(TokenType tt) { return peek().type() == tt; }

        Token expect(TokenType tt) {
            var t = next();
            if (t.type() != tt) throw new RuntimeException(
                "Expected " + tt + " but got " + t.type() + " (\"" + t.value() + "\") at " + t.line() + ":" + t.column());
            return t;
        }

        private Token scan() {
            while (true) {
                skipWS();
                if (pos >= src.length()) return tok(TokenType.EOF, "", pos);
                int start = pos;
                char ch = src.charAt(pos);
                switch (ch) {
                case '{': adv(); return tok(TokenType.LBrace, "{", start);
                case '}': adv(); return tok(TokenType.RBrace, "}", start);
                case '(': adv(); return tok(TokenType.LParen, "(", start);
                case ')': adv(); return tok(TokenType.RParen, ")", start);
                case '[': adv(); return tok(TokenType.LBracket, "[", start);
                case ']': adv(); return tok(TokenType.RBracket, "]", start);
                case ':': adv(); return tok(TokenType.Colon, ":", start);
                case ',': adv(); return tok(TokenType.Comma, ",", start);
                case '|': adv(); return tok(TokenType.Pipe, "|", start);
                case '*': adv(); return tok(TokenType.Star, "*", start);
                case '?': adv(); return tok(TokenType.Question, "?", start);
                case '!': adv(); return tok(TokenType.Bang, "!", start);
                case '~': adv(); return tok(TokenType.Tilde, "~", start);
                case '@': adv(); return tok(TokenType.At, "@", start);
                case '^': adv(); return tok(TokenType.Caret, "^", start);
                case '#': adv(); return tok(TokenType.Hash, "#", start);
                case '=': adv(); return tok(TokenType.Equals, "=", start);
                }
                if (ch == '+' && at(1) == '+') { adv(); adv(); return tok(TokenType.PlusPlus, "++", start); }
                if (Character.isDigit(ch) || (ch == '-' && at(1) >= '0' && at(1) <= '9')) return scanNum(start);
                if (ch == '"' || ch == '\'') return scanStr(start);
                if (Character.isLetter(ch) || ch == '_') return scanId(start);
                adv(); // skip unrecognized character
            }
        }

        private Token tok(TokenType tt, String value, int offset) {
            int l = 1, c = 1;
            for (int i = 0; i < offset; i++) { if (src.charAt(i) == '\n') { l++; c = 1; } else c++; }
            return new Token(tt, value, l, c, offset);
        }

        private char at(int n) { int i = pos + n; return i < src.length() ? src.charAt(i) : '\0'; }
        private void adv() { if (src.charAt(pos) == '\n') { line++; col = 1; } else col++; pos++; }

        private void skipWS() {
            while (pos < src.length()) {
                char c = src.charAt(pos);
                if (c == ' ' || c == '\t' || c == '\r' || c == '\n') { adv(); continue; }
                if (c == '/' && at(1) == '/') { adv(); adv(); while (pos < src.length() && src.charAt(pos) != '\n') adv(); continue; }
                if (c == '/' && at(1) == '*') {
                    adv(); adv();
                    while (pos < src.length()) { if (src.charAt(pos) == '*' && at(1) == '/') { adv(); adv(); break; } adv(); }
                    continue;
                }
                break;
            }
        }

        private Token scanId(int s) {
            while (pos < src.length() && (Character.isLetterOrDigit(src.charAt(pos)) || src.charAt(pos) == '_')) adv();
            return tok(TokenType.Ident, src.substring(s, pos), s);
        }

        private Token scanNum(int s) {
            if (src.charAt(pos) == '-') adv();
            while (pos < src.length() && Character.isDigit(src.charAt(pos))) adv();
            if (pos < src.length() && src.charAt(pos) == '.' && at(1) >= '0' && at(1) <= '9') {
                adv();
                while (pos < src.length() && Character.isDigit(src.charAt(pos))) adv();
            }
            return tok(TokenType.Number, src.substring(s, pos), s);
        }

        private Token scanStr(int s) {
            char q = src.charAt(pos); adv(); int cs = pos;
            while (pos < src.length() && src.charAt(pos) != q) { if (src.charAt(pos) == '\\') { adv(); if (pos >= src.length()) break; } adv(); }
            String v = src.substring(cs, pos);
            if (pos < src.length()) adv();
            return tok(TokenType.String, v, s);
        }
    }

    // ── Parser ──

    private static final int MAX_DEPTH = 64;
    private static final int MAX_INPUT = 1_000_000;

    private final Lexer lex;
    private final List<Diagnostic> diag = new ArrayList<>();
    private int depth = 0;

    public KappaParser(String source) {
        if (source.length() > MAX_INPUT) throw new RuntimeException("Input too large: " + source.length() + " bytes (max " + MAX_INPUT + ")");
        this.lex = new Lexer(source);
    }

    public static KappaFile parse(String source) { return new KappaParser(source).parseFile(); }

    public KappaFile parseFile() {
        var entities = new ArrayList<Entity>();
        var enumDeclarations = new ArrayList<EnumDeclaration>();
        var entityNames = new HashSet<String>();
        while (true) {
            try {
                if (lex.check(TokenType.EOF)) break;
                // Named enum at file level: "enum Name (a|b|c)"
                if (lex.check(TokenType.Ident) && lex.peek().value().equals("enum")) {
                    lex.next(); // consume "enum"
                    String eName = lex.expect(TokenType.Ident).value();
                    lex.expect(TokenType.LParen);
                    var eValues = new ArrayList<String>();
                    eValues.add(lex.expect(TokenType.Ident).value());
                    while (lex.check(TokenType.Pipe)) { lex.next(); eValues.add(lex.expect(TokenType.Ident).value()); }
                    lex.expect(TokenType.RParen);
                    enumDeclarations.add(new EnumDeclaration(eName, eValues));
                    continue;
                }
                var ent = entity();
                if (entityNames.contains(ent.name())) {
                    addDiag("Duplicate entity name: '" + ent.name() + "'");
                }
                entityNames.add(ent.name());
                entities.add(ent);
            } catch (RuntimeException e) {
                addDiag(e.getMessage());
                recoverEntity();
            }
        }
        return new KappaFile(entities, enumDeclarations, new ArrayList<>(diag));
    }

    private Entity entity() {
        String name = lex.expect(TokenType.Ident).value();
        lex.expect(TokenType.LBrace);
        var fields = fieldList();
        lex.expect(TokenType.RBrace);
        var uniqueConstraints = new ArrayList<List<String>>();
        // @unique(fields) after closing }
        while (lex.check(TokenType.At)) {
            lex.next(); // @
            String keyword = lex.expect(TokenType.Ident).value();
            if (keyword.equals("unique") || keyword.equals("index")) {
                lex.expect(TokenType.LParen);
                var uc = new ArrayList<String>();
                uc.add(lex.expect(TokenType.Ident).value());
                while (lex.check(TokenType.Comma)) { lex.next(); uc.add(lex.expect(TokenType.Ident).value()); }
                lex.expect(TokenType.RParen);
                uniqueConstraints.add(uc);
            }
        }
        return new Entity(name, fields, uniqueConstraints);
    }

    private List<Field> fieldList() {
        var fields = new ArrayList<Field>();
        var fieldNames = new HashSet<String>();
        if (lex.check(TokenType.RBrace)) return fields;
        var f = field(fieldNames);
        if (f != null) fields.add(f);
        while (lex.check(TokenType.Comma)) {
            lex.next();
            if (lex.check(TokenType.RBrace)) break;
            var f2 = field(fieldNames);
            if (f2 != null) fields.add(f2);
        }
        return fields;
    }

    private Field field(Set<String> fieldNames) {
        try {
            String name = lex.expect(TokenType.Ident).value();
            lex.expect(TokenType.Colon);
            FieldType type = fieldType();
            boolean required = true, optional = false, immutable = false, indexed = false, unique = false, autoIncrement = false, hidden = false;
            Constraint constraint = null;
            loop: while (true) {
                switch (lex.peek().type()) {
                    case Star: lex.next(); required = true; break;
                    case Question: lex.next(); required = false; optional = true; break;
                    case Bang: lex.next(); immutable = true; break;
                    case Tilde: lex.next(); indexed = true; break;
                    case At: lex.next(); unique = true; break;
                    case Caret: lex.next(); hidden = true; break;
                    case PlusPlus: lex.next(); autoIncrement = true; break;
                    case LParen: constraint = constraint(); break;
                    default: break loop;
                }
            }
            // #format annotation after modifiers
            String format = null;
            if (lex.check(TokenType.Hash)) {
                lex.next(); // consume #
                format = lex.expect(TokenType.Ident).value();
            }
            Object def = defaultValue();
            // Semantic validation
            if (required && optional) {
                addDiag("Field '" + name + "' has conflicting modifiers '*' and '?'");
            }
            if (fieldNames.contains(name)) {
                addDiag("Duplicate field name '" + name + "'");
            }
            fieldNames.add(name);
            return new Field(name, type, required, optional, immutable, indexed, unique, autoIncrement, hidden, format, constraint, def);
        } catch (RuntimeException e) {
            addDiag(e.getMessage());
            recoverField();
            return null;
        }
    }

    private FieldType fieldType() {
        if (++depth > MAX_DEPTH) { depth--; throw new RuntimeException("Maximum nesting depth exceeded"); }
        try { return fieldTypeInner(); } finally { depth--; }
    }
    private FieldType fieldTypeInner() {
        if (lex.check(TokenType.LBracket)) {
            lex.next(); var el = fieldType(); lex.expect(TokenType.RBracket);
            return new ArrayType(el);
        }
        if (lex.check(TokenType.LParen)) {
            lex.next();
            var values = new ArrayList<String>();
            values.add(lex.expect(TokenType.Ident).value());
            while (lex.check(TokenType.Pipe)) { lex.next(); values.add(lex.expect(TokenType.Ident).value()); }
            lex.expect(TokenType.RParen);
            return new EnumType(values);
        }
        if (lex.check(TokenType.Ident)) {
            var tok = lex.next();
            if (TYPE_CODES.contains(tok.value())) return new PrimitiveType(tok.value());
            return new ReferenceType(tok.value());
        }
        var tok = lex.peek();
        throw new RuntimeException("Expected field type, got " + tok.type() + " at " + tok.line() + ":" + tok.column());
    }

    private Constraint constraint() {
        lex.expect(TokenType.LParen);
        Double min = null, max = null;
        if (lex.check(TokenType.Number)) min = Double.parseDouble(lex.next().value());
        if (lex.check(TokenType.Comma)) {
            lex.next();
            if (lex.check(TokenType.Number)) max = Double.parseDouble(lex.next().value());
        } else {
            max = min;
        }
        lex.expect(TokenType.RParen);
        return new Constraint(min, max);
    }

    private Object defaultValue() {
        if (!lex.check(TokenType.Equals)) return null;
        lex.next();
        var tok = lex.next();
        return switch (tok.type()) {
            case String -> tok.value();
            case Number -> Double.parseDouble(tok.value());
            case Ident -> switch (tok.value()) {
                case "true" -> Boolean.TRUE;
                case "false" -> Boolean.FALSE;
                case "null" -> null;
                default -> tok.value();
            };
            default -> throw new RuntimeException("Expected default value, got " + tok.type() + " at " + tok.line() + ":" + tok.column());
        };
    }

    private void addDiag(String msg) {
        var tok = lex.peek();
        diag.add(new Diagnostic(msg, tok.line(), tok.column(), tok.offset()));
    }

    private void recoverField() {
        while (true) {
            var t = lex.peek().type();
            if (t == TokenType.Comma || t == TokenType.RBrace || t == TokenType.EOF) return;
            lex.next();
        }
    }

    private void recoverEntity() {
        int depth = 0;
        while (true) {
            var t = lex.peek().type();
            if (t == TokenType.EOF) return;
            if (t == TokenType.LBrace) depth++;
            if (t == TokenType.RBrace) { lex.next(); if (depth <= 1) return; depth--; continue; }
            lex.next();
        }
    }
}
