"""Kappa dense notation parser. Generated by Kappa parser generator. Do not edit."""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional, Union, Callable
from enum import Enum


# ── Tokens ──

class TokenType(Enum):
    Ident = "Ident"
    Number = "Number"
    String = "String"
    LBrace = "LBrace"
    RBrace = "RBrace"
    LParen = "LParen"
    RParen = "RParen"
    LBracket = "LBracket"
    RBracket = "RBracket"
    Colon = "Colon"
    Comma = "Comma"
    Pipe = "Pipe"
    Star = "Star"
    Question = "Question"
    Bang = "Bang"
    Tilde = "Tilde"
    At = "At"
    Caret = "Caret"
    Hash = "Hash"
    PlusPlus = "PlusPlus"
    Equals = "Equals"
    EOF = "EOF"


@dataclass
class Token:
    type: TokenType
    value: str
    line: int
    column: int
    offset: int


# ── AST ──

TYPE_CODES = frozenset({"s", "t", "i", "f", "m", "b", "d", "dt", "id", "x"})


@dataclass
class PrimitiveType:
    kind: str = "primitive"
    code: str = ""


@dataclass
class ArrayType:
    kind: str = "array"
    element_type: "FieldType" = None  # type: ignore


@dataclass
class ReferenceType:
    kind: str = "reference"
    entity: str = ""


@dataclass
class EnumType:
    kind: str = "enum"
    values: list[str] = field(default_factory=list)


FieldType = Union[PrimitiveType, ArrayType, ReferenceType, EnumType]


@dataclass
class Constraint:
    min: Optional[float] = None
    max: Optional[float] = None


DefaultValue = Union[str, int, float, bool, None]


@dataclass
class Field:
    kind: str = "field"
    name: str = ""
    type: FieldType = None  # type: ignore
    required: bool = True
    optional: bool = False
    immutable: bool = False
    indexed: bool = False
    unique: bool = False
    auto_increment: bool = False
    hidden: bool = False
    format: Optional[str] = None
    constraint: Optional[Constraint] = None
    default: Optional[DefaultValue] = None


@dataclass
class EnumDeclaration:
    kind: str = "enum_declaration"
    name: str = ""
    values: list[str] = field(default_factory=list)


@dataclass
class Entity:
    kind: str = "entity"
    name: str = ""
    fields: list[Field] = field(default_factory=list)
    unique_constraints: list[list[str]] = field(default_factory=list)


@dataclass
class Diagnostic:
    message: str = ""
    line: int = 0
    column: int = 0
    offset: int = 0


@dataclass
class KappaFile:
    kind: str = "file"
    entities: list[Entity] = field(default_factory=list)
    enum_declarations: list[EnumDeclaration] = field(default_factory=list)
    diagnostics: list[Diagnostic] = field(default_factory=list)


# ── Lexer ──

class Lexer:
    def __init__(self, source: str):
        self._src = source
        self._pos = 0
        self._line = 1
        self._col = 1
        self._peeked: Optional[Token] = None

    def peek(self) -> Token:
        if self._peeked is None:
            self._peeked = self._scan()
        return self._peeked

    def next(self) -> Token:
        if self._peeked is not None:
            t = self._peeked
            self._peeked = None
            return t
        return self._scan()

    def check(self, tt: TokenType) -> bool:
        return self.peek().type == tt

    def expect(self, tt: TokenType) -> Token:
        t = self.next()
        if t.type != tt:
            raise ParseError(f"Expected {tt.value} but got {t.type.value} (\"{t.value}\") at {t.line}:{t.column}")
        return t

    def _scan(self) -> Token:
        while True:
            self._skip_ws()
            if self._pos >= len(self._src):
                return self._tok(TokenType.EOF, "", self._pos)
            start = self._pos
            ch = self._src[self._pos]

            single = {
        "{": TokenType.LBrace,
        "}": TokenType.RBrace,
        "(": TokenType.LParen,
        ")": TokenType.RParen,
        "[": TokenType.LBracket,
        "]": TokenType.RBracket,
        ":": TokenType.Colon,
        ",": TokenType.Comma,
        "|": TokenType.Pipe,
        "*": TokenType.Star,
        "?": TokenType.Question,
        "!": TokenType.Bang,
        "~": TokenType.Tilde,
        "@": TokenType.At,
        "^": TokenType.Caret,
        "#": TokenType.Hash,
        "=": TokenType.Equals,
            }
            if ch in single:
                self._adv()
                return self._tok(single[ch], ch, start)

            if ch == "+" and self._at(1) == "+":
                self._adv(); self._adv()
                return self._tok(TokenType.PlusPlus, "++", start)

            if ch.isdigit() or (ch == "-" and self._at(1).isdigit()):
                return self._scan_num(start)

            if ch in ('"', "'"):
                return self._scan_str(start)

            if ch.isalpha() or ch == "_":
                return self._scan_id(start)

            self._adv()  # skip unrecognized character

    def _tok(self, tt: TokenType, value: str, offset: int) -> Token:
        line, col = 1, 1
        for i in range(offset):
            if self._src[i] == "\n":
                line += 1; col = 1
            else:
                col += 1
        return Token(tt, value, line, col, offset)

    def _at(self, n: int) -> str:
        i = self._pos + n
        return self._src[i] if i < len(self._src) else "\0"

    def _adv(self) -> None:
        if self._src[self._pos] == "\n":
            self._line += 1; self._col = 1
        else:
            self._col += 1
        self._pos += 1

    def _skip_ws(self) -> None:
        while self._pos < len(self._src):
            ch = self._src[self._pos]
            if ch in (" ", "\t", "\r", "\n"):
                self._adv(); continue
            if ch == "/" and self._at(1) == "/":
                self._adv(); self._adv()
                while self._pos < len(self._src) and self._src[self._pos] != "\n":
                    self._adv()
                continue
            if ch == "/" and self._at(1) == "*":
                self._adv(); self._adv()
                while self._pos < len(self._src):
                    if self._src[self._pos] == "*" and self._at(1) == "/":
                        self._adv(); self._adv(); break
                    self._adv()
                continue
            break

    def _scan_id(self, s: int) -> Token:
        while self._pos < len(self._src) and (self._src[self._pos].isalnum() or self._src[self._pos] == "_"):
            self._adv()
        return self._tok(TokenType.Ident, self._src[s:self._pos], s)

    def _scan_num(self, s: int) -> Token:
        if self._src[self._pos] == "-":
            self._adv()
        while self._pos < len(self._src) and self._src[self._pos].isdigit():
            self._adv()
        if self._pos < len(self._src) and self._src[self._pos] == "." and self._at(1).isdigit():
            self._adv()
            while self._pos < len(self._src) and self._src[self._pos].isdigit():
                self._adv()
        return self._tok(TokenType.Number, self._src[s:self._pos], s)

    def _scan_str(self, s: int) -> Token:
        q = self._src[self._pos]; self._adv(); cs = self._pos
        while self._pos < len(self._src) and self._src[self._pos] != q:
            if self._src[self._pos] == "\\":
                self._adv()
                if self._pos >= len(self._src): break
            self._adv()
        v = self._src[cs:self._pos]
        if self._pos < len(self._src):
            self._adv()
        return self._tok(TokenType.String, v, s)


# ── Parser ──

class ParseError(Exception):
    pass


FieldCallback = Callable[[Field, str], None]
EntityCallback = Callable[[Entity], None]


MAX_DEPTH = 64
MAX_INPUT = 1_000_000


class Parser:
    def __init__(self, source: str, on_field: Optional[FieldCallback] = None, on_entity: Optional[EntityCallback] = None):
        if len(source) > MAX_INPUT:
            raise ParseError(f"Input too large: {len(source)} bytes (max {MAX_INPUT})")
        self._lex = Lexer(source)
        self._diag: list[Diagnostic] = []
        self._depth = 0
        self._on_field = on_field
        self._on_entity = on_entity

    def parse(self) -> KappaFile:
        entities: list[Entity] = []
        enum_declarations: list[EnumDeclaration] = []
        entity_names: set[str] = set()
        while True:
            try:
                if self._lex.check(TokenType.EOF):
                    break
                # Named enum at file level: "enum Name (a|b|c)"
                if self._lex.check(TokenType.Ident) and self._lex.peek().value == "enum":
                    self._lex.next()  # consume "enum"
                    name = self._lex.expect(TokenType.Ident).value
                    self._lex.expect(TokenType.LParen)
                    values = [self._lex.expect(TokenType.Ident).value]
                    while self._lex.check(TokenType.Pipe):
                        self._lex.next()
                        values.append(self._lex.expect(TokenType.Ident).value)
                    self._lex.expect(TokenType.RParen)
                    enum_declarations.append(EnumDeclaration(name=name, values=values))
                    continue
                ent = self._entity()
                if ent.name in entity_names:
                    self._diagnostic(ParseError(f"Duplicate entity name: '{ent.name}'"))
                entity_names.add(ent.name)
                entities.append(ent)
                if self._on_entity:
                    self._on_entity(ent)
            except ParseError as e:
                self._diagnostic(e)
                self._recover_entity()
        return KappaFile(entities=entities, enum_declarations=enum_declarations, diagnostics=self._diag)

    def _entity(self) -> Entity:
        name = self._lex.expect(TokenType.Ident).value
        self._lex.expect(TokenType.LBrace)
        fields = self._field_list(name)
        self._lex.expect(TokenType.RBrace)
        unique_constraints: list[list[str]] = []
        # @unique(fields) after closing }
        while self._lex.check(TokenType.At):
            self._lex.next()  # @
            keyword = self._lex.expect(TokenType.Ident).value
            if keyword in ("unique", "index"):
                self._lex.expect(TokenType.LParen)
                uc = [self._lex.expect(TokenType.Ident).value]
                while self._lex.check(TokenType.Comma):
                    self._lex.next()
                    uc.append(self._lex.expect(TokenType.Ident).value)
                self._lex.expect(TokenType.RParen)
                unique_constraints.append(uc)
        return Entity(name=name, fields=fields, unique_constraints=unique_constraints)

    def _field_list(self, entity_name: str) -> list[Field]:
        fields: list[Field] = []
        field_names: set[str] = set()
        if self._lex.check(TokenType.RBrace):
            return fields
        f = self._field(entity_name, field_names)
        if f:
            fields.append(f)
        while self._lex.check(TokenType.Comma):
            self._lex.next()
            if self._lex.check(TokenType.RBrace):
                break
            f2 = self._field(entity_name, field_names)
            if f2:
                fields.append(f2)
        return fields

    def _field(self, entity_name: str, field_names: set[str]) -> Optional[Field]:
        try:
            name = self._lex.expect(TokenType.Ident).value
            self._lex.expect(TokenType.Colon)
            ftype = self._field_type()
            mods = self._modifiers()
            # #format annotation after modifiers
            fmt: Optional[str] = None
            if self._lex.check(TokenType.Hash):
                self._lex.next()  # consume #
                fmt = self._lex.expect(TokenType.Ident).value
            default = self._default_value()
            # Semantic validation
            if mods["required"] and mods["optional"]:
                self._diagnostic(ParseError(f"Field '{name}' in '{entity_name}' has conflicting modifiers '*' and '?'"))
            if name in field_names:
                self._diagnostic(ParseError(f"Duplicate field name '{name}' in entity '{entity_name}'"))
            field_names.add(name)
            f = Field(
                name=name, type=ftype,
                required=mods["required"], optional=mods["optional"],
                immutable=mods["immutable"], indexed=mods["indexed"],
                unique=mods["unique"], auto_increment=mods["auto_increment"],
                hidden=mods["hidden"],
                format=fmt,
                constraint=mods.get("constraint"),
                default=default,
            )
            if self._on_field:
                self._on_field(f, entity_name)
            return f
        except ParseError as e:
            self._diagnostic(e)
            self._recover_field()
            return None

    def _field_type(self) -> FieldType:
        self._depth += 1
        if self._depth > MAX_DEPTH:
            self._depth -= 1
            raise ParseError(f"Maximum nesting depth exceeded at {self._lex.peek().line}:{self._lex.peek().column}")
        try:
            return self._field_type_inner()
        finally:
            self._depth -= 1

    def _field_type_inner(self) -> FieldType:
        tok = self._lex.peek()
        if tok.type == TokenType.LBracket:
            self._lex.expect(TokenType.LBracket)
            el = self._field_type()
            self._lex.expect(TokenType.RBracket)
            return ArrayType(element_type=el)
        if tok.type == TokenType.LParen:
            self._lex.expect(TokenType.LParen)
            values = [self._lex.expect(TokenType.Ident).value]
            while self._lex.check(TokenType.Pipe):
                self._lex.next()
                values.append(self._lex.expect(TokenType.Ident).value)
            self._lex.expect(TokenType.RParen)
            return EnumType(values=values)
        if tok.type == TokenType.Ident:
            self._lex.next()
            if tok.value in TYPE_CODES:
                return PrimitiveType(code=tok.value)
            return ReferenceType(entity=tok.value)
        raise ParseError(f"Expected field type, got {tok.type.value} at {tok.line}:{tok.column}")

    def _modifiers(self) -> dict:
        required = True
        optional = False
        immutable = False
        indexed = False
        unique = False
        auto_increment = False
        hidden = False
        constraint: Optional[Constraint] = None
        while True:
            tt = self._lex.peek().type
            if tt == TokenType.Star:
                self._lex.next()
                required = True
            elif tt == TokenType.Question:
                self._lex.next()
                required = False
                optional = True
            elif tt == TokenType.LParen:
                constraint = self._constraint()
            elif tt == TokenType.Bang:
                self._lex.next()
                immutable = True
            elif tt == TokenType.Tilde:
                self._lex.next()
                indexed = True
            elif tt == TokenType.At:
                self._lex.next()
                unique = True
            elif tt == TokenType.Caret:
                self._lex.next()
                hidden = True
            elif tt == TokenType.PlusPlus:
                self._lex.next()
                auto_increment = True
            else:
                break
        return {"required": required, "optional": optional, "immutable": immutable,
                "indexed": indexed, "unique": unique, "auto_increment": auto_increment,
                "hidden": hidden, "constraint": constraint}

    def _constraint(self) -> Constraint:
        self._lex.expect(TokenType.LParen)
        mn: Optional[float] = None
        mx: Optional[float] = None
        if self._lex.check(TokenType.Number):
            mn = float(self._lex.next().value)
            if mn == 0.0: mn = 0.0  # normalize -0.0
        if self._lex.check(TokenType.Comma):
            self._lex.next()
            if self._lex.check(TokenType.Number):
                mx = float(self._lex.next().value)
                if mx == 0.0: mx = 0.0  # normalize -0.0
        else:
            mx = mn
        self._lex.expect(TokenType.RParen)
        if mn is not None and mx is not None and mn > mx:
            self._diagnostic(ParseError(f"Invalid constraint: min ({mn}) > max ({mx})"))
        return Constraint(min=mn, max=mx)

    def _default_value(self) -> Optional[DefaultValue]:
        if not self._lex.check(TokenType.Equals):
            return None
        self._lex.next()
        tok = self._lex.next()
        if tok.type == TokenType.String:
            return tok.value
        if tok.type == TokenType.Number:
            v = float(tok.value)
            return int(v) if v == int(v) else v
        if tok.type == TokenType.Ident:
            if tok.value == "true":
                return True
            if tok.value == "false":
                return False
            if tok.value == "null":
                return None
            return tok.value
        raise ParseError(f"Expected default value, got {tok.type.value} at {tok.line}:{tok.column}")

    def _diagnostic(self, e: Exception) -> None:
        tok = self._lex.peek()
        self._diag.append(Diagnostic(message=str(e), line=tok.line, column=tok.column, offset=tok.offset))

    def _recover_field(self) -> None:
        while True:
            t = self._lex.peek().type
            if t in (TokenType.Comma, TokenType.RBrace, TokenType.EOF):
                return
            self._lex.next()

    def _recover_entity(self) -> None:
        depth = 0
        while True:
            t = self._lex.peek().type
            if t == TokenType.EOF:
                return
            if t == TokenType.LBrace:
                depth += 1
            if t == TokenType.RBrace:
                self._lex.next()
                if depth <= 1:
                    return
                depth -= 1
                continue
            self._lex.next()


# ── Streaming Parser ──

class StreamingParser:
    def __init__(self):
        self._buf = ""
        self._entity_name: Optional[str] = None
        self._fields: list[Field] = []
        self._paren_depth = 0
        self._bracket_depth = 0
        self._in_string = False
        self._string_quote = ""
        self._escaped = False
        self._in_line_comment = False
        self._prev_char = ""
        self._field_handlers: list[FieldCallback] = []
        self._entity_handlers: list[EntityCallback] = []

    def on_field(self, fn: FieldCallback) -> "StreamingParser":
        self._field_handlers.append(fn); return self

    def on_entity(self, fn: EntityCallback) -> "StreamingParser":
        self._entity_handlers.append(fn); return self

    def feed(self, ch: str) -> None:
        if self._in_string:
            self._buf += ch
            if self._escaped:
                self._escaped = False
            elif ch == "\\":
                self._escaped = True
            elif ch == self._string_quote:
                self._in_string = False
            self._prev_char = ch; return

        if ch in ('"', "'"):
            self._in_string = True; self._string_quote = ch
            self._buf += ch; self._prev_char = ch; return

        if self._in_line_comment:
            if ch == "\n":
                self._in_line_comment = False
            self._prev_char = ch; return

        if ch == "/" and self._prev_char == "/":
            self._buf = self._buf[:-1]; self._in_line_comment = True
            self._prev_char = ch; return

        self._buf += ch
        if ch == "(": self._paren_depth += 1
        elif ch == ")": self._paren_depth -= 1
        elif ch == "[": self._bracket_depth += 1
        elif ch == "]": self._bracket_depth -= 1

        if ch == "{" and self._entity_name is None and self._paren_depth == 0:
            header = self._buf[:-1].strip()
            if header and header.isidentifier():
                self._entity_name = header; self._fields = []; self._buf = ""
            self._prev_char = ch; return

        if (self._entity_name is not None and self._paren_depth == 0
                and self._bracket_depth == 0 and ch in (",", "}")):
            field_text = self._buf[:-1].strip()
            if field_text:
                self._emit_field(field_text)
            self._buf = ""
            if ch == "}":
                entity = Entity(name=self._entity_name, fields=list(self._fields))
                for fn in self._entity_handlers:
                    fn(entity)
                self._entity_name = None; self._fields = []
        self._prev_char = ch

    def write(self, text: str) -> None:
        for ch in text:
            self.feed(ch)

    def end(self) -> list[Field]:
        remaining = self._buf.strip()
        if remaining and self._entity_name is not None:
            self._emit_field(remaining)
        return list(self._fields)

    def _emit_field(self, text: str) -> None:
        parser = Parser(f"_K {{ {text} }}")
        result = parser.parse()
        if result.diagnostics:
            return
        if result.entities and result.entities[0].fields:
            f = result.entities[0].fields[0]
            self._fields.append(f)
            for fn in self._field_handlers:
                fn(f, self._entity_name or "")


# ── Public API ──

def parse(source: str) -> KappaFile:
    return Parser(source).parse()
