// Package kappa provides a parser for Kappa dense notation.
// Generated by Kappa parser generator. Do not edit.
package kappa

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"
)

// ── Tokens ──

type TokenType int

const (
	TokenIdent TokenType = iota
	TokenNumber
	TokenString
	TokenLBrace
	TokenRBrace
	TokenLParen
	TokenRParen
	TokenLBracket
	TokenRBracket
	TokenColon
	TokenComma
	TokenPipe
	TokenStar
	TokenQuestion
	TokenBang
	TokenTilde
	TokenAt
	TokenCaret
	TokenHash
	TokenPlusPlus
	TokenEquals
	TokenEOF
)

var tokenNames = map[TokenType]string{
	TokenIdent: "Ident",
	TokenNumber: "Number",
	TokenString: "String",
	TokenLBrace: "LBrace",
	TokenRBrace: "RBrace",
	TokenLParen: "LParen",
	TokenRParen: "RParen",
	TokenLBracket: "LBracket",
	TokenRBracket: "RBracket",
	TokenColon: "Colon",
	TokenComma: "Comma",
	TokenPipe: "Pipe",
	TokenStar: "Star",
	TokenQuestion: "Question",
	TokenBang: "Bang",
	TokenTilde: "Tilde",
	TokenAt: "At",
	TokenCaret: "Caret",
	TokenHash: "Hash",
	TokenPlusPlus: "PlusPlus",
	TokenEquals: "Equals",
	TokenEOF: "EOF",
}

func (t TokenType) String() string { return tokenNames[t] }

type Token struct {
	Type   TokenType
	Value  string
	Line   int
	Column int
	Offset int
}

// ── AST ──

type FieldType interface{ fieldType() }

type PrimitiveType struct{ Code string }
type ArrayType struct{ ElementType FieldType }
type ReferenceType struct{ Entity string }
type EnumType struct{ Values []string }

func (PrimitiveType) fieldType() {}
func (ArrayType) fieldType()     {}
func (ReferenceType) fieldType() {}
func (EnumType) fieldType()      {}

type Constraint struct {
	Min *float64
	Max *float64
}

type DefaultValue interface{}

type Field struct {
	Name             string
	Type             FieldType
	Required         bool
	Optional         bool
	Immutable        bool
	Indexed          bool
	Unique           bool
	AutoIncrement    bool
	Hidden           bool
	Format           string
	Constraint       *Constraint
	Default          DefaultValue
}

type EnumDeclaration struct {
	Name   string
	Values []string
}

type Entity struct {
	Name              string
	Fields            []Field
	UniqueConstraints [][]string
}

type Diagnostic struct {
	Message string
	Line    int
	Column  int
	Offset  int
}

type KappaFile struct {
	Entities         []Entity
	EnumDeclarations []EnumDeclaration
	Diagnostics      []Diagnostic
}

func isTypeCode(s string) bool {
	switch s {
	case "s", "t", "i", "f", "m", "b", "d", "dt", "id", "x":
		return true
	}
	return false
}

// ── Lexer ──

type Lexer struct {
	src    []rune
	pos    int
	line   int
	col    int
	peeked *Token
}

func NewLexer(source string) *Lexer {
	return &Lexer{src: []rune(source), pos: 0, line: 1, col: 1}
}

func (l *Lexer) peek() Token {
	if l.peeked == nil {
		t := l.scan()
		l.peeked = &t
	}
	return *l.peeked
}

func (l *Lexer) next() Token {
	if l.peeked != nil {
		t := *l.peeked
		l.peeked = nil
		return t
	}
	return l.scan()
}

func (l *Lexer) check(tt TokenType) bool { return l.peek().Type == tt }

func (l *Lexer) expect(tt TokenType) (Token, error) {
	t := l.next()
	if t.Type != tt {
		return t, fmt.Errorf("expected %s but got %s (%q) at %d:%d", tt, t.Type, t.Value, t.Line, t.Column)
	}
	return t, nil
}

func (l *Lexer) scan() Token {
	for {
		l.skipWS()
		if l.pos >= len(l.src) {
			return l.tok(TokenEOF, "", l.pos)
		}
		start := l.pos
		ch := l.src[l.pos]
		switch ch {
	case '{':
		l.adv()
		return l.tok(TokenLBrace, "{", start)
	case '}':
		l.adv()
		return l.tok(TokenRBrace, "}", start)
	case '(':
		l.adv()
		return l.tok(TokenLParen, "(", start)
	case ')':
		l.adv()
		return l.tok(TokenRParen, ")", start)
	case '[':
		l.adv()
		return l.tok(TokenLBracket, "[", start)
	case ']':
		l.adv()
		return l.tok(TokenRBracket, "]", start)
	case ':':
		l.adv()
		return l.tok(TokenColon, ":", start)
	case ',':
		l.adv()
		return l.tok(TokenComma, ",", start)
	case '|':
		l.adv()
		return l.tok(TokenPipe, "|", start)
	case '*':
		l.adv()
		return l.tok(TokenStar, "*", start)
	case '?':
		l.adv()
		return l.tok(TokenQuestion, "?", start)
	case '!':
		l.adv()
		return l.tok(TokenBang, "!", start)
	case '~':
		l.adv()
		return l.tok(TokenTilde, "~", start)
	case '@':
		l.adv()
		return l.tok(TokenAt, "@", start)
	case '^':
		l.adv()
		return l.tok(TokenCaret, "^", start)
	case '#':
		l.adv()
		return l.tok(TokenHash, "#", start)
	case '=':
		l.adv()
		return l.tok(TokenEquals, "=", start)
		case '+':
			if l.at(1) == '+' {
				l.adv(); l.adv()
				return l.tok(TokenPlusPlus, "++", start)
			}
		case '"', '\'':
			return l.scanStr(start)
		case '-':
			if l.at(1) >= '0' && l.at(1) <= '9' {
				return l.scanNum(start)
			}
		}
		if ch >= '0' && ch <= '9' {
			return l.scanNum(start)
		}
		if unicode.IsLetter(ch) || ch == '_' {
			return l.scanId(start)
		}
		l.adv() // skip unrecognized character
	}
}

func (l *Lexer) tok(tt TokenType, value string, offset int) Token {
	line, col := 1, 1
	for i := 0; i < offset && i < len(l.src); i++ {
		if l.src[i] == '\n' { line++; col = 1 } else { col++ }
	}
	return Token{tt, value, line, col, offset}
}

func (l *Lexer) at(n int) rune {
	i := l.pos + n
	if i < len(l.src) { return l.src[i] }
	return 0
}

func (l *Lexer) adv() {
	if l.pos < len(l.src) {
		if l.src[l.pos] == '\n' { l.line++; l.col = 1 } else { l.col++ }
		l.pos++
	}
}

func (l *Lexer) skipWS() {
	for l.pos < len(l.src) {
		ch := l.src[l.pos]
		if ch == ' ' || ch == '\t' || ch == '\r' || ch == '\n' { l.adv(); continue }
		if ch == '/' && l.at(1) == '/' {
			l.adv(); l.adv()
			for l.pos < len(l.src) && l.src[l.pos] != '\n' { l.adv() }
			continue
		}
		if ch == '/' && l.at(1) == '*' {
			l.adv(); l.adv()
			for l.pos < len(l.src) {
				if l.src[l.pos] == '*' && l.at(1) == '/' { l.adv(); l.adv(); break }
				l.adv()
			}
			continue
		}
		break
	}
}

func (l *Lexer) scanId(s int) Token {
	for l.pos < len(l.src) && (unicode.IsLetter(l.src[l.pos]) || unicode.IsDigit(l.src[l.pos]) || l.src[l.pos] == '_') { l.adv() }
	return l.tok(TokenIdent, string(l.src[s:l.pos]), s)
}

func (l *Lexer) scanNum(s int) Token {
	if l.src[l.pos] == '-' { l.adv() }
	for l.pos < len(l.src) && l.src[l.pos] >= '0' && l.src[l.pos] <= '9' { l.adv() }
	if l.pos < len(l.src) && l.src[l.pos] == '.' && l.at(1) >= '0' && l.at(1) <= '9' {
		l.adv()
		for l.pos < len(l.src) && l.src[l.pos] >= '0' && l.src[l.pos] <= '9' { l.adv() }
	}
	return l.tok(TokenNumber, string(l.src[s:l.pos]), s)
}

func (l *Lexer) scanStr(s int) Token {
	q := l.src[l.pos]; l.adv(); cs := l.pos
	for l.pos < len(l.src) && l.src[l.pos] != q {
		if l.src[l.pos] == '\\' { l.adv(); if l.pos >= len(l.src) { break } }
		l.adv()
	}
	v := string(l.src[cs:l.pos])
	if l.pos < len(l.src) { l.adv() }
	return l.tok(TokenString, v, s)
}

// ── Parser ──

const maxDepth = 64
const maxInput = 1_000_000

type Parser struct {
	lex   *Lexer
	diag  []Diagnostic
	depth int
}

func NewParser(source string) *Parser {
	return &Parser{lex: NewLexer(source)}
}

func Parse(source string) KappaFile {
	if len(source) > maxInput {
		return KappaFile{Entities: make([]Entity, 0), EnumDeclarations: make([]EnumDeclaration, 0), Diagnostics: []Diagnostic{{Message: fmt.Sprintf("Input too large: %d bytes (max %d)", len(source), maxInput)}}}
	}
	return NewParser(source).Parse()
}

func (p *Parser) Parse() KappaFile {
	entities := make([]Entity, 0)
	enumDeclarations := make([]EnumDeclaration, 0)
	entityNames := make(map[string]bool)
	for {
		if p.lex.check(TokenEOF) { break }
		// Named enum at file level: "enum Name (a|b|c)"
		if p.lex.check(TokenIdent) && p.lex.peek().Value == "enum" {
			p.lex.next() // consume "enum"
			ed, err := p.parseEnumDecl()
			if err != nil {
				p.addDiag(err.Error())
				p.recoverEntity()
				continue
			}
			enumDeclarations = append(enumDeclarations, ed)
			continue
		}
		ent, err := p.entity()
		if err != nil {
			p.addDiag(err.Error())
			p.recoverEntity()
			continue
		}
		if entityNames[ent.Name] {
			p.addDiag(fmt.Sprintf("Duplicate entity name: '%s'", ent.Name))
		}
		entityNames[ent.Name] = true
		entities = append(entities, ent)
	}
	return KappaFile{Entities: entities, EnumDeclarations: enumDeclarations, Diagnostics: p.diag}
}

func (p *Parser) parseEnumDecl() (EnumDeclaration, error) {
	nameTok, err := p.lex.expect(TokenIdent)
	if err != nil { return EnumDeclaration{}, err }
	if _, err := p.lex.expect(TokenLParen); err != nil { return EnumDeclaration{}, err }
	v, err := p.lex.expect(TokenIdent)
	if err != nil { return EnumDeclaration{}, err }
	values := []string{v.Value}
	for p.lex.check(TokenPipe) {
		p.lex.next()
		v2, err := p.lex.expect(TokenIdent)
		if err != nil { return EnumDeclaration{}, err }
		values = append(values, v2.Value)
	}
	if _, err := p.lex.expect(TokenRParen); err != nil { return EnumDeclaration{}, err }
	return EnumDeclaration{Name: nameTok.Value, Values: values}, nil
}

func (p *Parser) entity() (Entity, error) {
	nameTok, err := p.lex.expect(TokenIdent)
	if err != nil { return Entity{}, err }
	if _, err := p.lex.expect(TokenLBrace); err != nil { return Entity{}, err }
	fields, err := p.fieldList()
	if err != nil { return Entity{}, err }
	if _, err := p.lex.expect(TokenRBrace); err != nil { return Entity{}, err }
	uniqueConstraints := make([][]string, 0)
	// @unique(fields) after closing }
	for p.lex.check(TokenAt) {
		p.lex.next() // @
		kw, err := p.lex.expect(TokenIdent)
		if err != nil { return Entity{}, err }
		if kw.Value == "unique" || kw.Value == "index" {
			if _, err := p.lex.expect(TokenLParen); err != nil { return Entity{}, err }
			f, err := p.lex.expect(TokenIdent)
			if err != nil { return Entity{}, err }
			uc := []string{f.Value}
			for p.lex.check(TokenComma) {
				p.lex.next()
				f2, err := p.lex.expect(TokenIdent)
				if err != nil { return Entity{}, err }
				uc = append(uc, f2.Value)
			}
			if _, err := p.lex.expect(TokenRParen); err != nil { return Entity{}, err }
			uniqueConstraints = append(uniqueConstraints, uc)
		}
	}
	return Entity{Name: nameTok.Value, Fields: fields, UniqueConstraints: uniqueConstraints}, nil
}

func (p *Parser) fieldList() ([]Field, error) {
	fields := make([]Field, 0)
	fieldNames := make(map[string]bool)
	if p.lex.check(TokenRBrace) { return fields, nil }
	f, err := p.field(fieldNames)
	if err != nil {
		p.addDiag(err.Error())
		p.recoverField()
	} else {
		fields = append(fields, f)
	}
	for p.lex.check(TokenComma) {
		p.lex.next()
		if p.lex.check(TokenRBrace) { break }
		f, err := p.field(fieldNames)
		if err != nil {
			p.addDiag(err.Error())
			p.recoverField()
		} else {
			fields = append(fields, f)
		}
	}
	return fields, nil
}

func (p *Parser) recoverField() {
	for {
		tt := p.lex.peek().Type
		if tt == TokenComma || tt == TokenRBrace || tt == TokenEOF { return }
		p.lex.next()
	}
}

func (p *Parser) field(fieldNames map[string]bool) (Field, error) {
	nameTok, err := p.lex.expect(TokenIdent)
	if err != nil { return Field{}, err }
	if _, err := p.lex.expect(TokenColon); err != nil { return Field{}, err }
	ft, err := p.fieldType()
	if err != nil { return Field{}, err }
	m, err := p.modifiers()
	if err != nil { return Field{}, err }
	// #format annotation after modifiers
	if p.lex.check(TokenHash) {
		p.lex.next() // consume #
		fmtTok, err := p.lex.expect(TokenIdent)
		if err != nil { return Field{}, err }
		m.Format = fmtTok.Value
	}
	def, err := p.defaultValue()
	if err != nil { return Field{}, err }
	// Semantic validation
	if m.Required && m.Optional {
		p.addDiag(fmt.Sprintf("Field '%s' has conflicting modifiers '*' and '?'", nameTok.Value))
	}
	if fieldNames[nameTok.Value] {
		p.addDiag(fmt.Sprintf("Duplicate field name '%s'", nameTok.Value))
	}
	fieldNames[nameTok.Value] = true
	m.Name = nameTok.Value
	m.Type = ft
	m.Default = def
	return m, nil
}

func (p *Parser) fieldType() (FieldType, error) {
	p.depth++
	if p.depth > maxDepth { p.depth--; return nil, fmt.Errorf("maximum nesting depth exceeded") }
	defer func() { p.depth-- }()
	if p.lex.check(TokenLBracket) {
		p.lex.next()
		el, err := p.fieldType()
		if err != nil { return nil, err }
		if _, err := p.lex.expect(TokenRBracket); err != nil { return nil, err }
		return ArrayType{ElementType: el}, nil
	}
	if p.lex.check(TokenLParen) {
		p.lex.next()
		tok, err := p.lex.expect(TokenIdent)
		if err != nil { return nil, err }
		values := []string{tok.Value}
		for p.lex.check(TokenPipe) {
			p.lex.next()
			v, err := p.lex.expect(TokenIdent)
			if err != nil { return nil, err }
			values = append(values, v.Value)
		}
		if _, err := p.lex.expect(TokenRParen); err != nil { return nil, err }
		return EnumType{Values: values}, nil
	}
	if p.lex.check(TokenIdent) {
		tok := p.lex.next()
		if isTypeCode(tok.Value) { return PrimitiveType{Code: tok.Value}, nil }
		return ReferenceType{Entity: tok.Value}, nil
	}
	tok := p.lex.peek()
	return nil, fmt.Errorf("expected field type, got %s at %d:%d", tok.Type, tok.Line, tok.Column)
}

func (p *Parser) modifiers() (Field, error) {
	m := Field{Required: true}
	for {
		switch p.lex.peek().Type {
		case TokenStar:
			p.lex.next()
			m.Required = true
		case TokenQuestion:
			p.lex.next()
			m.Required = false
			m.Optional = true
		case TokenBang:
			p.lex.next()
			m.Immutable = true
		case TokenTilde:
			p.lex.next()
			m.Indexed = true
		case TokenAt:
			p.lex.next()
			m.Unique = true
		case TokenCaret:
			p.lex.next()
			m.Hidden = true
		case TokenPlusPlus:
			p.lex.next()
			m.AutoIncrement = true
		case TokenLParen:
			c, err := p.constraint()
			if err != nil { return m, err }
			m.Constraint = &c
		default:
			return m, nil
		}
	}
}

func (p *Parser) constraint() (Constraint, error) {
	if _, err := p.lex.expect(TokenLParen); err != nil { return Constraint{}, err }
	var mn, mx *float64
	if p.lex.check(TokenNumber) {
		v, _ := strconv.ParseFloat(p.lex.next().Value, 64)
		mn = &v
	}
	if p.lex.check(TokenComma) {
		p.lex.next()
		if p.lex.check(TokenNumber) {
			v, _ := strconv.ParseFloat(p.lex.next().Value, 64)
			mx = &v
		}
	} else {
		mx = mn
	}
	if _, err := p.lex.expect(TokenRParen); err != nil { return Constraint{}, err }
	return Constraint{Min: mn, Max: mx}, nil
}

func (p *Parser) defaultValue() (DefaultValue, error) {
	if !p.lex.check(TokenEquals) { return nil, nil }
	p.lex.next()
	tok := p.lex.next()
	switch tok.Type {
	case TokenString:
		return tok.Value, nil
	case TokenNumber:
		v, _ := strconv.ParseFloat(tok.Value, 64)
		return v, nil
	case TokenIdent:
		switch tok.Value {
		case "true": return true, nil
		case "false": return false, nil
		case "null": return nil, nil
		default: return tok.Value, nil
		}
	}
	return nil, fmt.Errorf("expected default value, got %s at %d:%d", tok.Type, tok.Line, tok.Column)
}

func (p *Parser) addDiag(msg string) {
	tok := p.lex.peek()
	p.diag = append(p.diag, Diagnostic{Message: msg, Line: tok.Line, Column: tok.Column, Offset: tok.Offset})
}

func (p *Parser) recoverEntity() {
	depth := 0
	for {
		tt := p.lex.peek().Type
		if tt == TokenEOF { return }
		if tt == TokenLBrace { depth++ }
		if tt == TokenRBrace { p.lex.next(); if depth <= 1 { return }; depth--; continue }
		p.lex.next()
	}
}

// suppress unused import warnings
var _ = strings.Contains
