/** Generated by Kappa parser generator. Do not edit. */

export type { TypeCode, PrimitiveType, ArrayType, ReferenceType, EnumType, FieldType, Constraint, DefaultValue, Field, EnumDeclaration, Entity, KappaFile, Diagnostic } from './ast.js';
export { TYPE_CODES } from './ast.js';
export { Parser } from './parser.js';
export type { ParseOptions, FieldCallback, EntityCallback } from './parser.js';
export { StreamingParser } from './stream.js';
export type { FieldHandler, EntityHandler, ErrorHandler } from './stream.js';

import { Parser } from './parser.js';
import type { KappaFile } from './ast.js';

export function parse(input: string): KappaFile {
  return new Parser(input).parse();
}
