/** Generated by Kappa parser generator. Do not edit. */

export enum TokenType {
  Ident,
  Number,
  String,
  LBrace,
  RBrace,
  LParen,
  RParen,
  LBracket,
  RBracket,
  Colon,
  Comma,
  Pipe,
  Star,
  Question,
  Bang,
  Tilde,
  At,
  Caret,
  Hash,
  PlusPlus,
  Equals,
  EOF,
}

export interface Token {
  type: TokenType;
  value: string;
  line: number;
  column: number;
  offset: number;
}

export class Lexer {
  private src: string;
  private pos = 0;
  private line = 1;
  private col = 1;
  private peeked: Token | null = null;

  constructor(source: string) { this.src = source; }

  peek(): Token {
    if (this.peeked === null) this.peeked = this.scan();
    return this.peeked;
  }

  next(): Token {
    if (this.peeked !== null) { const t = this.peeked; this.peeked = null; return t; }
    return this.scan();
  }

  check(type: TokenType): boolean { return this.peek().type === type; }

  expect(type: TokenType): Token {
    const t = this.next();
    if (t.type !== type) throw new Error(`Expected ${TokenType[type]} but got ${TokenType[t.type]} ("${t.value}") at ${t.line}:${t.column}`);
    return t;
  }

  error(msg: string, tok?: Token): Error {
    const t = tok ?? this.peek();
    return new Error(`${msg} at ${t.line}:${t.column}`);
  }

  private scan(): Token {
    while (true) {
      this.skipWS();
      if (this.pos >= this.src.length) return this.tok(TokenType.EOF, '', this.pos);
      const start = this.pos;
      const ch = this.src[this.pos];
      const single: Record<string, TokenType> = {
      '{': TokenType.LBrace,
      '}': TokenType.RBrace,
      '(': TokenType.LParen,
      ')': TokenType.RParen,
      '[': TokenType.LBracket,
      ']': TokenType.RBracket,
      ':': TokenType.Colon,
      ',': TokenType.Comma,
      '|': TokenType.Pipe,
      '*': TokenType.Star,
      '?': TokenType.Question,
      '!': TokenType.Bang,
      '~': TokenType.Tilde,
      '@': TokenType.At,
      '^': TokenType.Caret,
      '#': TokenType.Hash,
      '=': TokenType.Equals,
      };
      if (ch in single) { this.adv(); return this.tok(single[ch], ch, start); }
      if (ch === '+' && this.at(1) === '+') { this.adv(); this.adv(); return this.tok(TokenType.PlusPlus, '++', start); }
      if (this.isDigit(ch) || (ch === '-' && this.isDigit(this.at(1)))) return this.scanNum(start);
      if (ch === '"' || ch === "'") return this.scanStr(start);
      if (this.isIdStart(ch)) return this.scanId(start);
      this.adv(); // skip unrecognized character
    }
  }

  private tok(type: TokenType, value: string, offset: number): Token {
    let line = 1, col = 1;
    for (let i = 0; i < offset; i++) { if (this.src[i] === '\n') { line++; col = 1; } else col++; }
    return { type, value, line, column: col, offset };
  }

  private at(n: number): string { const i = this.pos + n; return i < this.src.length ? this.src[i] : '\0'; }
  private adv(): void { if (this.src[this.pos] === '\n') { this.line++; this.col = 1; } else this.col++; this.pos++; }

  private skipWS(): void {
    while (this.pos < this.src.length) {
      const ch = this.src[this.pos];
      if (ch === ' ' || ch === '\t' || ch === '\r' || ch === '\n') { this.adv(); continue; }
      if (ch === '/' && this.at(1) === '/') { this.adv(); this.adv(); while (this.pos < this.src.length && this.src[this.pos] !== '\n') this.adv(); continue; }
      if (ch === '/' && this.at(1) === '*') { this.adv(); this.adv(); while (this.pos < this.src.length) { if (this.src[this.pos] === '*' && this.at(1) === '/') { this.adv(); this.adv(); break; } this.adv(); } continue; }
      break;
    }
  }

  private scanId(s: number): Token { while (this.pos < this.src.length && this.isIdChar(this.src[this.pos])) this.adv(); return this.tok(TokenType.Ident, this.src.slice(s, this.pos), s); }

  private scanNum(s: number): Token {
    if (this.src[this.pos] === '-') this.adv();
    while (this.pos < this.src.length && this.isDigit(this.src[this.pos])) this.adv();
    if (this.pos < this.src.length && this.src[this.pos] === '.' && this.isDigit(this.at(1))) { this.adv(); while (this.pos < this.src.length && this.isDigit(this.src[this.pos])) this.adv(); }
    return this.tok(TokenType.Number, this.src.slice(s, this.pos), s);
  }

  private scanStr(s: number): Token {
    const q = this.src[this.pos]; this.adv(); const cs = this.pos;
    while (this.pos < this.src.length && this.src[this.pos] !== q) { if (this.src[this.pos] === '\\') { this.adv(); if (this.pos >= this.src.length) break; } this.adv(); }
    const v = this.src.slice(cs, this.pos);
    if (this.pos < this.src.length) this.adv();
    return this.tok(TokenType.String, v, s);
  }

  private isDigit(c: string | undefined): boolean { return c !== undefined && c >= '0' && c <= '9'; }
  private isIdStart(c: string): boolean { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c === '_'; }
  private isIdChar(c: string): boolean { return this.isIdStart(c) || this.isDigit(c); }
}
