/** Generated by Kappa parser generator. Do not edit. */

import { Lexer, TokenType } from './lexer.js';
import { TYPE_CODES, type TypeCode, type KappaFile, type Entity, type EnumDeclaration, type Field, type FieldType, type Constraint, type DefaultValue, type Diagnostic } from './ast.js';

export type FieldCallback = (field: Field, entityName: string) => void;
export type EntityCallback = (entity: Entity) => void;
export interface ParseOptions { onField?: FieldCallback; onEntity?: EntityCallback; }

const MAX_DEPTH = 64;
const MAX_INPUT = 1_000_000;

export class Parser {
  private lex: Lexer;
  private diag: Diagnostic[] = [];
  private depth = 0;
  private onField?: FieldCallback;
  private onEntity?: EntityCallback;

  constructor(source: string, opts?: ParseOptions) {
    if (source.length > MAX_INPUT) throw new Error(`Input too large: ${source.length} bytes (max ${MAX_INPUT})`);
    this.lex = new Lexer(source);
    this.onField = opts?.onField;
    this.onEntity = opts?.onEntity;
  }

  parse(): KappaFile {
    const entities: Entity[] = [];
    const enumDeclarations: EnumDeclaration[] = [];
    const entityNames = new Set<string>();
    while (true) {
      try {
        if (this.lex.check(TokenType.EOF)) break;
        // Named enum at file level: "enum Name (a|b|c)"
        if (this.lex.check(TokenType.Ident) && this.lex.peek().value === 'enum') {
          this.lex.next(); // consume "enum"
          const name = this.lex.expect(TokenType.Ident).value;
          this.lex.expect(TokenType.LParen);
          const values: string[] = [this.lex.expect(TokenType.Ident).value];
          while (this.lex.check(TokenType.Pipe)) { this.lex.next(); values.push(this.lex.expect(TokenType.Ident).value); }
          this.lex.expect(TokenType.RParen);
          enumDeclarations.push({ kind: 'enum_declaration', name, values });
          continue;
        }
        const ent = this.entity();
        if (entityNames.has(ent.name)) {
          this.diagnostic(new Error(`Duplicate entity name: '${ent.name}'`));
        }
        entityNames.add(ent.name);
        entities.push(ent);
        this.onEntity?.(ent);
      } catch (e) { this.diagnostic(e); this.recoverEntity(); }
    }
    return { kind: 'file', entities, enumDeclarations, diagnostics: this.diag };
  }

  private entity(): Entity {
    const name = this.lex.expect(TokenType.Ident).value;
    this.lex.expect(TokenType.LBrace);
    const fields = this.fieldList(name);
    this.lex.expect(TokenType.RBrace);
    const uniqueConstraints: string[][] = [];
    // @unique(fields) after closing }
    while (this.lex.check(TokenType.At)) {
      this.lex.next(); // @
      const keyword = this.lex.expect(TokenType.Ident).value;
      if (keyword === 'unique' || keyword === 'index') {
        this.lex.expect(TokenType.LParen);
        const uc: string[] = [this.lex.expect(TokenType.Ident).value];
        while (this.lex.check(TokenType.Comma)) { this.lex.next(); uc.push(this.lex.expect(TokenType.Ident).value); }
        this.lex.expect(TokenType.RParen);
        uniqueConstraints.push(uc);
      }
    }
    return { kind: 'entity', name, fields, uniqueConstraints };
  }

  private fieldList(entityName: string): Field[] {
    const fields: Field[] = [];
    const fieldNames = new Set<string>();
    if (this.lex.check(TokenType.RBrace)) return fields;
    const f = this.field(entityName, fieldNames);
    if (f) fields.push(f);
    while (this.lex.check(TokenType.Comma)) {
      this.lex.next();
      if (this.lex.check(TokenType.RBrace)) break;
      const f2 = this.field(entityName, fieldNames);
      if (f2) fields.push(f2);
    }
    return fields;
  }

  private field(entityName: string, fieldNames: Set<string>): Field | null {
    try {
      const name = this.lex.expect(TokenType.Ident).value;
      this.lex.expect(TokenType.Colon);
      const type = this.fieldType();
      const mods = this.modifiers();
      // #format annotation after modifiers
      let format: string | undefined;
      if (this.lex.check(TokenType.Hash)) {
        this.lex.next(); // consume #
        format = this.lex.expect(TokenType.Ident).value;
      }
      const def = this.defaultValue();
      // Semantic validation
      if (mods.required && mods.optional) {
        this.diagnostic(new Error(`Field '${name}' in '${entityName}' has conflicting modifiers '*' and '?'`));
      }
      if (fieldNames.has(name)) {
        this.diagnostic(new Error(`Duplicate field name '${name}' in entity '${entityName}'`));
      }
      fieldNames.add(name);
      const f: Field = { kind: 'field', name, type, required: mods.required, optional: mods.optional, immutable: mods.immutable, indexed: mods.indexed, unique: mods.unique, autoIncrement: mods.autoIncrement, hidden: mods.hidden };
      if (format !== undefined) f.format = format;
      if (mods.constraint) f.constraint = mods.constraint;
      if (def !== undefined) f.default = def;
      this.onField?.(f, entityName);
      return f;
    } catch (e) { this.diagnostic(e); this.recoverField(); return null; }
  }

  private fieldType(): FieldType {
    if (++this.depth > MAX_DEPTH) throw this.lex.error('Maximum nesting depth exceeded');
    try {
    const tok = this.lex.peek();
    if (tok.type === TokenType.LBracket) { this.lex.expect(TokenType.LBracket); const el = this.fieldType(); this.lex.expect(TokenType.RBracket); return { kind: 'array', elementType: el }; }
    if (tok.type === TokenType.LParen) {
      this.lex.expect(TokenType.LParen);
      const values: string[] = [this.lex.expect(TokenType.Ident).value];
      while (this.lex.check(TokenType.Pipe)) { this.lex.next(); values.push(this.lex.expect(TokenType.Ident).value); }
      this.lex.expect(TokenType.RParen);
      return { kind: 'enum', values };
    }
    if (tok.type === TokenType.Ident) {
      this.lex.next();
      if (TYPE_CODES.has(tok.value)) return { kind: 'primitive', code: tok.value as TypeCode };
      return { kind: 'reference', entity: tok.value };
    }
    throw this.lex.error(`Expected field type, got ${TokenType[tok.type]}`, tok);
    } finally { this.depth--; }
  }

  private modifiers() {
    let required = true, optional = false, immutable = false, indexed = false, unique = false, autoIncrement = false, hidden = false;
    let constraint: Constraint | undefined;
    loop: while (true) {
      switch (this.lex.peek().type) {
        case TokenType.Star: this.lex.next(); required = true; break;
        case TokenType.Question: this.lex.next(); required = false; optional = true; break;
        case TokenType.Bang: this.lex.next(); immutable = true; break;
        case TokenType.Tilde: this.lex.next(); indexed = true; break;
        case TokenType.At: this.lex.next(); unique = true; break;
        case TokenType.Caret: this.lex.next(); hidden = true; break;
        case TokenType.PlusPlus: this.lex.next(); autoIncrement = true; break;
        case TokenType.LParen: constraint = this.constraint(); break;
        default: break loop;
      }
    }
    return { required, optional, immutable, indexed, unique, autoIncrement, hidden, constraint };
  }

  private constraint(): Constraint {
    this.lex.expect(TokenType.LParen);
    let min: number | undefined, max: number | undefined;
    if (this.lex.check(TokenType.Number)) { min = parseFloat(this.lex.next().value); if (Object.is(min, -0)) min = 0; }
    if (this.lex.check(TokenType.Comma)) { this.lex.next(); if (this.lex.check(TokenType.Number)) { max = parseFloat(this.lex.next().value); if (Object.is(max, -0)) max = 0; } } else { max = min; }
    this.lex.expect(TokenType.RParen);
    if (min !== undefined && max !== undefined && min > max) {
      this.diagnostic(new Error(`Invalid constraint: min (${min}) > max (${max})`));
    }
    const c: Constraint = {};
    if (min !== undefined) c.min = min;
    if (max !== undefined) c.max = max;
    return c;
  }

  private defaultValue(): DefaultValue | undefined {
    if (!this.lex.check(TokenType.Equals)) return undefined;
    this.lex.next();
    const tok = this.lex.next();
    switch (tok.type) {
      case TokenType.String: return tok.value;
      case TokenType.Number: return parseFloat(tok.value);
      case TokenType.Ident:
        if (tok.value === 'true') return true;
        if (tok.value === 'false') return false;
        if (tok.value === 'null') return null;
        return tok.value;
      default: throw this.lex.error(`Expected default value, got ${TokenType[tok.type]}`, tok);
    }
  }

  private diagnostic(e: unknown): void {
    const msg = e instanceof Error ? e.message : String(e);
    const tok = this.lex.peek();
    this.diag.push({ message: msg, line: tok.line, column: tok.column, offset: tok.offset });
  }

  private recoverField(): void { while (true) { const t = this.lex.peek().type; if (t === TokenType.Comma || t === TokenType.RBrace || t === TokenType.EOF) return; this.lex.next(); } }

  private recoverEntity(): void {
    let depth = 0;
    while (true) {
      const t = this.lex.peek().type;
      if (t === TokenType.EOF) return;
      if (t === TokenType.LBrace) depth++;
      if (t === TokenType.RBrace) { this.lex.next(); if (depth <= 1) return; depth--; continue; }
      this.lex.next();
    }
  }
}
