/** Generated by Kappa parser generator. Do not edit. */

import { Parser } from './parser.js';
import type { Entity, Field, Diagnostic } from './ast.js';

export type FieldHandler = (field: Field, entityName: string) => void;
export type EntityHandler = (entity: Entity) => void;
export type ErrorHandler = (diagnostic: Diagnostic) => void;

export class StreamingParser {
  private buf = '';
  private entityName: string | null = null;
  private fields: Field[] = [];
  private parenDepth = 0;
  private bracketDepth = 0;
  private inString = false;
  private stringQuote = '';
  private escaped = false;
  private inLineComment = false;
  private prevChar = '';
  private fieldHandlers: FieldHandler[] = [];
  private entityHandlers: EntityHandler[] = [];
  private errorHandlers: ErrorHandler[] = [];

  onField(fn: FieldHandler): this { this.fieldHandlers.push(fn); return this; }
  onEntity(fn: EntityHandler): this { this.entityHandlers.push(fn); return this; }
  onError(fn: ErrorHandler): this { this.errorHandlers.push(fn); return this; }

  feed(ch: string): void {
    if (this.inString) {
      this.buf += ch;
      if (this.escaped) { this.escaped = false; }
      else if (ch === '\\') { this.escaped = true; }
      else if (ch === this.stringQuote) { this.inString = false; }
      this.prevChar = ch; return;
    }
    if (ch === '"' || ch === "'") { this.inString = true; this.stringQuote = ch; this.buf += ch; this.prevChar = ch; return; }
    if (this.inLineComment) { if (ch === '\n') this.inLineComment = false; this.prevChar = ch; return; }
    if (ch === '/' && this.prevChar === '/') { this.buf = this.buf.slice(0, -1); this.inLineComment = true; this.prevChar = ch; return; }

    this.buf += ch;
    if (ch === '(') this.parenDepth++;
    else if (ch === ')') this.parenDepth--;
    else if (ch === '[') this.bracketDepth++;
    else if (ch === ']') this.bracketDepth--;

    if (ch === '{' && this.entityName === null && this.parenDepth === 0) {
      const header = this.buf.slice(0, -1).trim();
      if (header && /^[A-Za-z_]\w*$/.test(header)) {
        this.entityName = header; this.fields = []; this.buf = '';
      }
      this.prevChar = ch; return;
    }

    if (this.entityName !== null && this.parenDepth === 0 && this.bracketDepth === 0 && (ch === ',' || ch === '}')) {
      const fieldText = this.buf.slice(0, -1).trim();
      if (fieldText) this.emitField(fieldText);
      this.buf = '';
      if (ch === '}') {
        const entity: Entity = { kind: 'entity', name: this.entityName, fields: [...this.fields], uniqueConstraints: [] };
        for (const fn of this.entityHandlers) fn(entity);
        this.entityName = null; this.fields = [];
      }
    }
    this.prevChar = ch;
  }

  write(text: string): void { for (let i = 0; i < text.length; i++) this.feed(text[i]); }

  end(): Field[] {
    const remaining = this.buf.trim();
    if (remaining && this.entityName !== null) this.emitField(remaining);
    return [...this.fields];
  }

  private emitField(text: string): void {
    const input = `_K { ${text} }`;
    const parser = new Parser(input);
    const result = parser.parse();
    if (result.diagnostics.length > 0) { for (const d of result.diagnostics) for (const fn of this.errorHandlers) fn(d); return; }
    const ent = result.entities[0];
    if (ent && ent.fields.length > 0) {
      const field = ent.fields[0];
      this.fields.push(field);
      for (const fn of this.fieldHandlers) fn(field, this.entityName!);
    }
  }
}
