/** Generate Rust parser source files. */

import { tokens, typeCodes, modifiers } from './spec.js';

export function emitRust(): Record<string, string> {
  return {
    'lib.rs': lib(),
    '../Cargo.toml': cargo(),
  };
}

function cargo(): string {
  return `[package]
name = "kappa-parser"
version = "0.1.0"
edition = "2021"
description = "Kappa dense notation parser"
license = "MIT"
`;
}

function lib(): string {
  const tokenVariants = tokens.map(t => `    ${t.name},`).join('\n');
  const singleChars = tokens
    .filter(t => t.literal && t.literal.length === 1)
    .map(t => `            '${t.literal}' => { self.adv(); return self.tok(TokenType::${t.name}, "${t.literal}", start); }`)
    .join('\n');
  const typeCodeMatches = typeCodes.map(t => `"${t.code}"`).join(' | ');
  // Filter out Star and Question — handled explicitly in modifiers()
  const modCases = modifiers
    .filter(m => m.token !== 'Star' && m.token !== 'Question')
    .map(m => `            TokenType::${m.token} => { self.lex.next(); ${toSnake(m.field)} = true; }`)
    .join('\n');

  return `//! Kappa dense notation parser. Generated by Kappa parser generator. Do not edit.

use std::fmt;

// ── Tokens ──

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenType {
${tokenVariants}
}

impl fmt::Display for TokenType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[derive(Debug, Clone)]
pub struct Token {
    pub token_type: TokenType,
    pub value: String,
    pub line: usize,
    pub column: usize,
    pub offset: usize,
}

// ── AST ──

#[derive(Debug, Clone, PartialEq)]
pub enum FieldType {
    Primitive { code: String },
    Array { element_type: Box<FieldType> },
    Reference { entity: String },
    Enum { values: Vec<String> },
}

#[derive(Debug, Clone)]
pub struct Constraint {
    pub min: Option<f64>,
    pub max: Option<f64>,
}

#[derive(Debug, Clone)]
pub enum DefaultValue {
    Str(String),
    Num(f64),
    Bool(bool),
    Null,
}

#[derive(Debug, Clone)]
pub struct Field {
    pub name: String,
    pub field_type: FieldType,
    pub required: bool,
    pub optional: bool,
    pub immutable: bool,
    pub indexed: bool,
    pub unique: bool,
    pub auto_increment: bool,
    pub hidden: bool,
    pub format: Option<String>,
    pub constraint: Option<Constraint>,
    pub default: Option<DefaultValue>,
}

#[derive(Debug, Clone)]
pub struct EnumDeclaration {
    pub name: String,
    pub values: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct Entity {
    pub name: String,
    pub fields: Vec<Field>,
    pub unique_constraints: Vec<Vec<String>>,
}

#[derive(Debug, Clone)]
pub struct Diagnostic {
    pub message: String,
    pub line: usize,
    pub column: usize,
    pub offset: usize,
}

#[derive(Debug)]
pub struct KappaFile {
    pub entities: Vec<Entity>,
    pub enum_declarations: Vec<EnumDeclaration>,
    pub diagnostics: Vec<Diagnostic>,
}

#[derive(Debug)]
pub struct ParseError(pub String);

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for ParseError {}

fn is_type_code(s: &str) -> bool {
    matches!(s, ${typeCodeMatches})
}

// ── Lexer ──

pub struct Lexer {
    src: Vec<char>,
    pos: usize,
    line: usize,
    col: usize,
    peeked: Option<Token>,
}

impl Lexer {
    pub fn new(source: &str) -> Self {
        Lexer { src: source.chars().collect(), pos: 0, line: 1, col: 1, peeked: None }
    }

    pub fn peek(&mut self) -> &Token {
        if self.peeked.is_none() {
            self.peeked = Some(self.scan());
        }
        self.peeked.as_ref().unwrap()
    }

    pub fn next(&mut self) -> Token {
        if let Some(t) = self.peeked.take() { return t; }
        self.scan()
    }

    pub fn check(&mut self, tt: TokenType) -> bool {
        self.peek().token_type == tt
    }

    pub fn expect(&mut self, tt: TokenType) -> Result<Token, ParseError> {
        let t = self.next();
        if t.token_type != tt {
            return Err(ParseError(format!("Expected {} but got {} (\\"{}\\") at {}:{}", tt, t.token_type, t.value, t.line, t.column)));
        }
        Ok(t)
    }

    fn scan(&mut self) -> Token {
        loop {
            self.skip_ws();
            if self.pos >= self.src.len() {
                return self.tok(TokenType::EOF, "", self.pos);
            }
            let start = self.pos;
            let ch = self.src[self.pos];
            match ch {
${singleChars}
                '+' if self.at(1) == '+' => { self.adv(); self.adv(); return self.tok(TokenType::PlusPlus, "++", start); }
                '"' | '\\'' => return self.scan_str(start),
                '-' if self.at(1).is_ascii_digit() => return self.scan_num(start),
                _ if ch.is_ascii_digit() => return self.scan_num(start),
                _ if ch.is_ascii_alphabetic() || ch == '_' => return self.scan_id(start),
                _ => { self.adv(); } // skip unrecognized character
            }
        }
    }

    fn tok(&self, tt: TokenType, value: &str, offset: usize) -> Token {
        let (mut line, mut col) = (1usize, 1usize);
        for i in 0..offset {
            if self.src[i] == '\\n' { line += 1; col = 1; } else { col += 1; }
        }
        Token { token_type: tt, value: value.to_string(), line, column: col, offset }
    }

    fn at(&self, n: usize) -> char {
        let i = self.pos + n;
        if i < self.src.len() { self.src[i] } else { '\\0' }
    }

    fn adv(&mut self) {
        if self.pos < self.src.len() {
            if self.src[self.pos] == '\\n' { self.line += 1; self.col = 1; } else { self.col += 1; }
            self.pos += 1;
        }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.src.len() {
            let ch = self.src[self.pos];
            if ch == ' ' || ch == '\\t' || ch == '\\r' || ch == '\\n' { self.adv(); continue; }
            if ch == '/' && self.at(1) == '/' {
                self.adv(); self.adv();
                while self.pos < self.src.len() && self.src[self.pos] != '\\n' { self.adv(); }
                continue;
            }
            if ch == '/' && self.at(1) == '*' {
                self.adv(); self.adv();
                while self.pos < self.src.len() {
                    if self.src[self.pos] == '*' && self.at(1) == '/' { self.adv(); self.adv(); break; }
                    self.adv();
                }
                continue;
            }
            break;
        }
    }

    fn scan_id(&mut self, s: usize) -> Token {
        while self.pos < self.src.len() && (self.src[self.pos].is_ascii_alphanumeric() || self.src[self.pos] == '_') { self.adv(); }
        let val: String = self.src[s..self.pos].iter().collect();
        self.tok(TokenType::Ident, &val, s)
    }

    fn scan_num(&mut self, s: usize) -> Token {
        if self.src[self.pos] == '-' { self.adv(); }
        while self.pos < self.src.len() && self.src[self.pos].is_ascii_digit() { self.adv(); }
        if self.pos < self.src.len() && self.src[self.pos] == '.' && self.at(1).is_ascii_digit() {
            self.adv();
            while self.pos < self.src.len() && self.src[self.pos].is_ascii_digit() { self.adv(); }
        }
        let val: String = self.src[s..self.pos].iter().collect();
        self.tok(TokenType::Number, &val, s)
    }

    fn scan_str(&mut self, s: usize) -> Token {
        let q = self.src[self.pos]; self.adv(); let cs = self.pos;
        while self.pos < self.src.len() && self.src[self.pos] != q {
            if self.src[self.pos] == '\\\\' { self.adv(); if self.pos >= self.src.len() { break; } }
            self.adv();
        }
        let val: String = self.src[cs..self.pos].iter().collect();
        if self.pos < self.src.len() { self.adv(); }
        self.tok(TokenType::String, &val, s)
    }
}

// ── Parser ──

const MAX_DEPTH: usize = 64;
const MAX_INPUT: usize = 1_000_000;

pub struct Parser {
    lex: Lexer,
    diag: Vec<Diagnostic>,
    depth: usize,
}

impl Parser {
    pub fn new(source: &str) -> Self {
        Parser { lex: Lexer::new(source), diag: Vec::new(), depth: 0 }
    }

    pub fn parse(&mut self) -> KappaFile {
        let mut entities = Vec::new();
        let mut enum_declarations = Vec::new();
        let mut entity_names = std::collections::HashSet::new();
        loop {
            if self.lex.check(TokenType::EOF) { break; }
            // Named enum at file level: "enum Name (a|b|c)"
            if self.lex.check(TokenType::Ident) && self.lex.peek().value == "enum" {
                self.lex.next(); // consume "enum"
                match self.parse_enum_decl() {
                    Ok(ed) => enum_declarations.push(ed),
                    Err(e) => { self.add_diag(&e.0); self.recover_entity(); }
                }
                continue;
            }
            match self.entity() {
                Ok(ent) => {
                    if entity_names.contains(&ent.name) {
                        self.add_diag(&format!("Duplicate entity name: '{}'", ent.name));
                    }
                    entity_names.insert(ent.name.clone());
                    entities.push(ent);
                }
                Err(e) => { self.add_diag(&e.0); self.recover_entity(); }
            }
        }
        KappaFile { entities, enum_declarations, diagnostics: std::mem::take(&mut self.diag) }
    }

    fn parse_enum_decl(&mut self) -> Result<EnumDeclaration, ParseError> {
        let name = self.lex.expect(TokenType::Ident)?.value;
        self.lex.expect(TokenType::LParen)?;
        let mut values = vec![self.lex.expect(TokenType::Ident)?.value];
        while self.lex.check(TokenType::Pipe) { self.lex.next(); values.push(self.lex.expect(TokenType::Ident)?.value); }
        self.lex.expect(TokenType::RParen)?;
        Ok(EnumDeclaration { name, values })
    }

    fn entity(&mut self) -> Result<Entity, ParseError> {
        let name = self.lex.expect(TokenType::Ident)?.value;
        self.lex.expect(TokenType::LBrace)?;
        let fields = self.field_list(&name)?;
        self.lex.expect(TokenType::RBrace)?;
        let mut unique_constraints: Vec<Vec<String>> = Vec::new();
        // @unique(fields) after closing }
        while self.lex.check(TokenType::At) {
            self.lex.next(); // @
            let keyword = self.lex.expect(TokenType::Ident)?.value;
            if keyword == "unique" || keyword == "index" {
                self.lex.expect(TokenType::LParen)?;
                let mut uc = vec![self.lex.expect(TokenType::Ident)?.value];
                while self.lex.check(TokenType::Comma) { self.lex.next(); uc.push(self.lex.expect(TokenType::Ident)?.value); }
                self.lex.expect(TokenType::RParen)?;
                unique_constraints.push(uc);
            }
        }
        Ok(Entity { name, fields, unique_constraints })
    }

    fn field_list(&mut self, _entity_name: &str) -> Result<Vec<Field>, ParseError> {
        let mut fields = Vec::new();
        let mut field_names = std::collections::HashSet::new();
        if self.lex.check(TokenType::RBrace) { return Ok(fields); }
        match self.field(_entity_name, &mut field_names) {
            Ok(Some(f)) => fields.push(f),
            Ok(None) => {}
            Err(e) => { self.add_diag(&e.0); self.recover_field(); }
        }
        while self.lex.check(TokenType::Comma) {
            self.lex.next();
            if self.lex.check(TokenType::RBrace) { break; }
            match self.field(_entity_name, &mut field_names) {
                Ok(Some(f)) => fields.push(f),
                Ok(None) => {}
                Err(e) => { self.add_diag(&e.0); self.recover_field(); }
            }
        }
        Ok(fields)
    }

    fn field(&mut self, entity_name: &str, field_names: &mut std::collections::HashSet<String>) -> Result<Option<Field>, ParseError> {
        let name = self.lex.expect(TokenType::Ident)?.value;
        self.lex.expect(TokenType::Colon)?;
        let field_type = self.field_type()?;
        let (required, optional, immutable, indexed, unique, auto_increment, hidden, constraint) = self.modifiers()?;
        // #format annotation after modifiers
        let format = if self.lex.check(TokenType::Hash) {
            self.lex.next(); // consume #
            Some(self.lex.expect(TokenType::Ident)?.value)
        } else {
            None
        };
        let default = self.default_value()?;
        // Semantic validation (warnings as diagnostics)
        if required && optional {
            self.add_diag(&format!("Field '{}' in '{}' has conflicting modifiers '*' and '?'", name, entity_name));
        }
        if field_names.contains(&name) {
            self.add_diag(&format!("Duplicate field name '{}' in entity '{}'", name, entity_name));
        }
        field_names.insert(name.clone());
        Ok(Some(Field { name, field_type, required, optional, immutable, indexed, unique, auto_increment, hidden, format, constraint, default }))
    }

    fn field_type(&mut self) -> Result<FieldType, ParseError> {
        self.depth += 1;
        if self.depth > MAX_DEPTH { self.depth -= 1; return Err(ParseError("Maximum nesting depth exceeded".to_string())); }
        let result = self.field_type_inner();
        self.depth -= 1;
        result
    }

    fn field_type_inner(&mut self) -> Result<FieldType, ParseError> {
        if self.lex.check(TokenType::LBracket) {
            self.lex.expect(TokenType::LBracket)?;
            let el = self.field_type()?;
            self.lex.expect(TokenType::RBracket)?;
            return Ok(FieldType::Array { element_type: Box::new(el) });
        }
        if self.lex.check(TokenType::LParen) {
            self.lex.expect(TokenType::LParen)?;
            let mut values = vec![self.lex.expect(TokenType::Ident)?.value];
            while self.lex.check(TokenType::Pipe) { self.lex.next(); values.push(self.lex.expect(TokenType::Ident)?.value); }
            self.lex.expect(TokenType::RParen)?;
            return Ok(FieldType::Enum { values });
        }
        if self.lex.check(TokenType::Ident) {
            let tok = self.lex.next();
            if is_type_code(&tok.value) { return Ok(FieldType::Primitive { code: tok.value }); }
            return Ok(FieldType::Reference { entity: tok.value });
        }
        let tok = self.lex.peek();
        Err(ParseError(format!("Expected field type, got {} at {}:{}", tok.token_type, tok.line, tok.column)))
    }

    fn modifiers(&mut self) -> Result<(bool, bool, bool, bool, bool, bool, bool, Option<Constraint>), ParseError> {
        let mut required = true;
        let mut optional = false;
        let mut immutable = false;
        let mut indexed = false;
        let mut unique = false;
        let mut auto_increment = false;
        let mut hidden = false;
        let mut constraint: Option<Constraint> = None;
        loop {
            match self.lex.peek().token_type {
                TokenType::Star => { self.lex.next(); required = true; }
                TokenType::Question => { self.lex.next(); required = false; optional = true; }
${modCases}
                TokenType::LParen => { constraint = Some(self.parse_constraint()?); }
                _ => break,
            }
        }
        Ok((required, optional, immutable, indexed, unique, auto_increment, hidden, constraint))
    }

    fn parse_constraint(&mut self) -> Result<Constraint, ParseError> {
        self.lex.expect(TokenType::LParen)?;
        let min = if self.lex.check(TokenType::Number) { Some(self.lex.next().value.parse::<f64>().unwrap_or(0.0)) } else { None };
        let max;
        if self.lex.check(TokenType::Comma) {
            self.lex.next();
            max = if self.lex.check(TokenType::Number) { Some(self.lex.next().value.parse::<f64>().unwrap_or(0.0)) } else { None };
        } else {
            max = min;
        }
        self.lex.expect(TokenType::RParen)?;
        Ok(Constraint { min, max })
    }

    fn default_value(&mut self) -> Result<Option<DefaultValue>, ParseError> {
        if !self.lex.check(TokenType::Equals) { return Ok(None); }
        self.lex.next();
        let tok = self.lex.next();
        match tok.token_type {
            TokenType::String => Ok(Some(DefaultValue::Str(tok.value))),
            TokenType::Number => Ok(Some(DefaultValue::Num(tok.value.parse::<f64>().unwrap_or(0.0)))),
            TokenType::Ident => match tok.value.as_str() {
                "true" => Ok(Some(DefaultValue::Bool(true))),
                "false" => Ok(Some(DefaultValue::Bool(false))),
                "null" => Ok(Some(DefaultValue::Null)),
                _ => Ok(Some(DefaultValue::Str(tok.value))),
            },
            _ => Err(ParseError(format!("Expected default value, got {} at {}:{}", tok.token_type, tok.line, tok.column))),
        }
    }

    fn add_diag(&mut self, msg: &str) {
        let tok = self.lex.peek();
        self.diag.push(Diagnostic { message: msg.to_string(), line: tok.line, column: tok.column, offset: tok.offset });
    }

    fn recover_field(&mut self) {
        loop {
            let tt = self.lex.peek().token_type;
            if tt == TokenType::Comma || tt == TokenType::RBrace || tt == TokenType::EOF { return; }
            self.lex.next();
        }
    }

    fn recover_entity(&mut self) {
        let mut depth = 0;
        loop {
            let tt = self.lex.peek().token_type;
            if tt == TokenType::EOF { return; }
            if tt == TokenType::LBrace { depth += 1; }
            if tt == TokenType::RBrace { self.lex.next(); if depth <= 1 { return; } depth -= 1; continue; }
            self.lex.next();
        }
    }
}

// ── Public API ──

pub fn parse(source: &str) -> KappaFile {
    if source.len() > MAX_INPUT {
        return KappaFile {
            entities: Vec::new(),
            enum_declarations: Vec::new(),
            diagnostics: vec![Diagnostic { message: format!("Input too large: {} bytes (max {})", source.len(), MAX_INPUT), line: 0, column: 0, offset: 0 }],
        };
    }
    Parser::new(source).parse()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_entity() {
        let result = parse("User { id: id*, email: s*@~ }");
        assert_eq!(result.entities.len(), 1);
        assert_eq!(result.entities[0].name, "User");
        assert_eq!(result.entities[0].fields.len(), 2);
        assert!(result.entities[0].fields[0].required);
        assert!(result.entities[0].fields[1].unique);
        assert!(result.entities[0].fields[1].indexed);
    }

    #[test]
    fn parse_v2_features() {
        let input = "enum Role (admin|editor|viewer)\\nUser { email: s#email, name: s(1,100), role: Role=viewer, password_hash: s^ } @unique(email)";
        let result = parse(input);
        assert_eq!(result.enum_declarations.len(), 1);
        assert_eq!(result.enum_declarations[0].name, "Role");
        assert_eq!(result.entities.len(), 1);
        assert_eq!(result.entities[0].unique_constraints.len(), 1);
        let email_field = &result.entities[0].fields[0];
        assert_eq!(email_field.format, Some("email".to_string()));
        let pw_field = &result.entities[0].fields[3];
        assert!(pw_field.hidden);
    }
}
`;
}

function toSnake(s: string): string {
  return s.replace(/[A-Z]/g, c => '_' + c.toLowerCase());
}
