/** Generate TypeScript parser source files. */

import { tokens, typeCodes, modifiers } from './spec.js';

export function emitTypeScript(): Record<string, string> {
  return {
    'ast.ts': ast(),
    'lexer.ts': lexer(),
    'parser.ts': parser(),
    'stream.ts': stream(),
    'index.ts': index(),
  };
}

// ── AST ──

function ast(): string {
  const typeUnion = typeCodes.map(t => `'${t.code}'`).join(' | ');
  const typeSet = typeCodes.map(t => `'${t.code}'`).join(', ');

  return `/** Generated by Kappa parser generator. Do not edit. */

export type TypeCode = ${typeUnion};
export const TYPE_CODES: ReadonlySet<string> = new Set([${typeSet}]);

export interface PrimitiveType { kind: 'primitive'; code: TypeCode; }
export interface ArrayType { kind: 'array'; elementType: FieldType; }
export interface ReferenceType { kind: 'reference'; entity: string; }
export interface EnumType { kind: 'enum'; values: string[]; }
export type FieldType = PrimitiveType | ArrayType | ReferenceType | EnumType;

export interface Constraint { min?: number; max?: number; }
export type DefaultValue = string | number | boolean | null;

export interface Field {
  kind: 'field';
  name: string;
  type: FieldType;
  required: boolean;
  optional: boolean;
  immutable: boolean;
  indexed: boolean;
  unique: boolean;
  autoIncrement: boolean;
  hidden: boolean;
  format?: string;
  constraint?: Constraint;
  default?: DefaultValue;
}

export interface EnumDeclaration { kind: 'enum_declaration'; name: string; values: string[]; }
export interface Entity { kind: 'entity'; name: string; fields: Field[]; uniqueConstraints: string[][]; }
export interface KappaFile { kind: 'file'; entities: Entity[]; enumDeclarations: EnumDeclaration[]; diagnostics: Diagnostic[]; }
export interface Diagnostic { message: string; line: number; column: number; offset: number; }
`;
}

// ── Lexer ──

function lexer(): string {
  const enumMembers = tokens.map(t => `  ${t.name},`).join('\n');
  const singleChars = tokens
    .filter(t => t.literal && t.literal.length === 1)
    .map(t => `      '${t.literal}': TokenType.${t.name},`)
    .join('\n');

  return `/** Generated by Kappa parser generator. Do not edit. */

export enum TokenType {
${enumMembers}
}

export interface Token {
  type: TokenType;
  value: string;
  line: number;
  column: number;
  offset: number;
}

export class Lexer {
  private src: string;
  private pos = 0;
  private line = 1;
  private col = 1;
  private peeked: Token | null = null;

  constructor(source: string) { this.src = source; }

  peek(): Token {
    if (this.peeked === null) this.peeked = this.scan();
    return this.peeked;
  }

  next(): Token {
    if (this.peeked !== null) { const t = this.peeked; this.peeked = null; return t; }
    return this.scan();
  }

  check(type: TokenType): boolean { return this.peek().type === type; }

  expect(type: TokenType): Token {
    const t = this.next();
    if (t.type !== type) throw new Error(\`Expected \${TokenType[type]} but got \${TokenType[t.type]} ("\${t.value}") at \${t.line}:\${t.column}\`);
    return t;
  }

  error(msg: string, tok?: Token): Error {
    const t = tok ?? this.peek();
    return new Error(\`\${msg} at \${t.line}:\${t.column}\`);
  }

  private scan(): Token {
    while (true) {
      this.skipWS();
      if (this.pos >= this.src.length) return this.tok(TokenType.EOF, '', this.pos);
      const start = this.pos;
      const ch = this.src[this.pos];
      const single: Record<string, TokenType> = {
${singleChars}
      };
      if (ch in single) { this.adv(); return this.tok(single[ch], ch, start); }
      if (ch === '+' && this.at(1) === '+') { this.adv(); this.adv(); return this.tok(TokenType.PlusPlus, '++', start); }
      if (this.isDigit(ch) || (ch === '-' && this.isDigit(this.at(1)))) return this.scanNum(start);
      if (ch === '"' || ch === "'") return this.scanStr(start);
      if (this.isIdStart(ch)) return this.scanId(start);
      this.adv(); // skip unrecognized character
    }
  }

  private tok(type: TokenType, value: string, offset: number): Token {
    let line = 1, col = 1;
    for (let i = 0; i < offset; i++) { if (this.src[i] === '\\n') { line++; col = 1; } else col++; }
    return { type, value, line, column: col, offset };
  }

  private at(n: number): string { const i = this.pos + n; return i < this.src.length ? this.src[i] : '\\0'; }
  private adv(): void { if (this.src[this.pos] === '\\n') { this.line++; this.col = 1; } else this.col++; this.pos++; }

  private skipWS(): void {
    while (this.pos < this.src.length) {
      const ch = this.src[this.pos];
      if (ch === ' ' || ch === '\\t' || ch === '\\r' || ch === '\\n') { this.adv(); continue; }
      if (ch === '/' && this.at(1) === '/') { this.adv(); this.adv(); while (this.pos < this.src.length && this.src[this.pos] !== '\\n') this.adv(); continue; }
      if (ch === '/' && this.at(1) === '*') { this.adv(); this.adv(); while (this.pos < this.src.length) { if (this.src[this.pos] === '*' && this.at(1) === '/') { this.adv(); this.adv(); break; } this.adv(); } continue; }
      break;
    }
  }

  private scanId(s: number): Token { while (this.pos < this.src.length && this.isIdChar(this.src[this.pos])) this.adv(); return this.tok(TokenType.Ident, this.src.slice(s, this.pos), s); }

  private scanNum(s: number): Token {
    if (this.src[this.pos] === '-') this.adv();
    while (this.pos < this.src.length && this.isDigit(this.src[this.pos])) this.adv();
    if (this.pos < this.src.length && this.src[this.pos] === '.' && this.isDigit(this.at(1))) { this.adv(); while (this.pos < this.src.length && this.isDigit(this.src[this.pos])) this.adv(); }
    return this.tok(TokenType.Number, this.src.slice(s, this.pos), s);
  }

  private scanStr(s: number): Token {
    const q = this.src[this.pos]; this.adv(); const cs = this.pos;
    while (this.pos < this.src.length && this.src[this.pos] !== q) { if (this.src[this.pos] === '\\\\') { this.adv(); if (this.pos >= this.src.length) break; } this.adv(); }
    const v = this.src.slice(cs, this.pos);
    if (this.pos < this.src.length) this.adv();
    return this.tok(TokenType.String, v, s);
  }

  private isDigit(c: string | undefined): boolean { return c !== undefined && c >= '0' && c <= '9'; }
  private isIdStart(c: string): boolean { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c === '_'; }
  private isIdChar(c: string): boolean { return this.isIdStart(c) || this.isDigit(c); }
}
`;
}

// ── Parser ──

function parser(): string {
  const modCases = modifiers
    .map(m => `        case TokenType.${m.token}: this.lex.next(); ${m.field} = true; break;`)
    .join('\n');
  return `/** Generated by Kappa parser generator. Do not edit. */

import { Lexer, TokenType } from './lexer.js';
import { TYPE_CODES, type TypeCode, type KappaFile, type Entity, type EnumDeclaration, type Field, type FieldType, type Constraint, type DefaultValue, type Diagnostic } from './ast.js';

export type FieldCallback = (field: Field, entityName: string) => void;
export type EntityCallback = (entity: Entity) => void;
export interface ParseOptions { onField?: FieldCallback; onEntity?: EntityCallback; }

const MAX_DEPTH = 64;
const MAX_INPUT = 1_000_000;

export class Parser {
  private lex: Lexer;
  private diag: Diagnostic[] = [];
  private depth = 0;
  private onField?: FieldCallback;
  private onEntity?: EntityCallback;

  constructor(source: string, opts?: ParseOptions) {
    if (source.length > MAX_INPUT) throw new Error(\`Input too large: \${source.length} bytes (max \${MAX_INPUT})\`);
    this.lex = new Lexer(source);
    this.onField = opts?.onField;
    this.onEntity = opts?.onEntity;
  }

  parse(): KappaFile {
    const entities: Entity[] = [];
    const enumDeclarations: EnumDeclaration[] = [];
    const entityNames = new Set<string>();
    while (true) {
      try {
        if (this.lex.check(TokenType.EOF)) break;
        // Named enum at file level: "enum Name (a|b|c)"
        if (this.lex.check(TokenType.Ident) && this.lex.peek().value === 'enum') {
          this.lex.next(); // consume "enum"
          const name = this.lex.expect(TokenType.Ident).value;
          this.lex.expect(TokenType.LParen);
          const values: string[] = [this.lex.expect(TokenType.Ident).value];
          while (this.lex.check(TokenType.Pipe)) { this.lex.next(); values.push(this.lex.expect(TokenType.Ident).value); }
          this.lex.expect(TokenType.RParen);
          enumDeclarations.push({ kind: 'enum_declaration', name, values });
          continue;
        }
        const ent = this.entity();
        if (entityNames.has(ent.name)) {
          this.diagnostic(new Error(\`Duplicate entity name: '\${ent.name}'\`));
        }
        entityNames.add(ent.name);
        entities.push(ent);
        this.onEntity?.(ent);
      } catch (e) { this.diagnostic(e); this.recoverEntity(); }
    }
    return { kind: 'file', entities, enumDeclarations, diagnostics: this.diag };
  }

  private entity(): Entity {
    const name = this.lex.expect(TokenType.Ident).value;
    this.lex.expect(TokenType.LBrace);
    const fields = this.fieldList(name);
    this.lex.expect(TokenType.RBrace);
    const uniqueConstraints: string[][] = [];
    // @unique(fields) after closing }
    while (this.lex.check(TokenType.At)) {
      this.lex.next(); // @
      const keyword = this.lex.expect(TokenType.Ident).value;
      if (keyword === 'unique' || keyword === 'index') {
        this.lex.expect(TokenType.LParen);
        const uc: string[] = [this.lex.expect(TokenType.Ident).value];
        while (this.lex.check(TokenType.Comma)) { this.lex.next(); uc.push(this.lex.expect(TokenType.Ident).value); }
        this.lex.expect(TokenType.RParen);
        uniqueConstraints.push(uc);
      }
    }
    return { kind: 'entity', name, fields, uniqueConstraints };
  }

  private fieldList(entityName: string): Field[] {
    const fields: Field[] = [];
    const fieldNames = new Set<string>();
    if (this.lex.check(TokenType.RBrace)) return fields;
    const f = this.field(entityName, fieldNames);
    if (f) fields.push(f);
    while (this.lex.check(TokenType.Comma)) {
      this.lex.next();
      if (this.lex.check(TokenType.RBrace)) break;
      const f2 = this.field(entityName, fieldNames);
      if (f2) fields.push(f2);
    }
    return fields;
  }

  private field(entityName: string, fieldNames: Set<string>): Field | null {
    try {
      const name = this.lex.expect(TokenType.Ident).value;
      this.lex.expect(TokenType.Colon);
      const type = this.fieldType();
      const mods = this.modifiers();
      // #format annotation after modifiers
      let format: string | undefined;
      if (this.lex.check(TokenType.Hash)) {
        this.lex.next(); // consume #
        format = this.lex.expect(TokenType.Ident).value;
      }
      const def = this.defaultValue();
      // Semantic validation
      if (mods.required && mods.optional) {
        this.diagnostic(new Error(\`Field '\${name}' in '\${entityName}' has conflicting modifiers '*' and '?'\`));
      }
      if (fieldNames.has(name)) {
        this.diagnostic(new Error(\`Duplicate field name '\${name}' in entity '\${entityName}'\`));
      }
      fieldNames.add(name);
      const f: Field = { kind: 'field', name, type, required: mods.required, optional: mods.optional, immutable: mods.immutable, indexed: mods.indexed, unique: mods.unique, autoIncrement: mods.autoIncrement, hidden: mods.hidden };
      if (format !== undefined) f.format = format;
      if (mods.constraint) f.constraint = mods.constraint;
      if (def !== undefined) f.default = def;
      this.onField?.(f, entityName);
      return f;
    } catch (e) { this.diagnostic(e); this.recoverField(); return null; }
  }

  private fieldType(): FieldType {
    if (++this.depth > MAX_DEPTH) throw this.lex.error('Maximum nesting depth exceeded');
    try {
    const tok = this.lex.peek();
    if (tok.type === TokenType.LBracket) { this.lex.expect(TokenType.LBracket); const el = this.fieldType(); this.lex.expect(TokenType.RBracket); return { kind: 'array', elementType: el }; }
    if (tok.type === TokenType.LParen) {
      this.lex.expect(TokenType.LParen);
      const values: string[] = [this.lex.expect(TokenType.Ident).value];
      while (this.lex.check(TokenType.Pipe)) { this.lex.next(); values.push(this.lex.expect(TokenType.Ident).value); }
      this.lex.expect(TokenType.RParen);
      return { kind: 'enum', values };
    }
    if (tok.type === TokenType.Ident) {
      this.lex.next();
      if (TYPE_CODES.has(tok.value)) return { kind: 'primitive', code: tok.value as TypeCode };
      return { kind: 'reference', entity: tok.value };
    }
    throw this.lex.error(\`Expected field type, got \${TokenType[tok.type]}\`, tok);
    } finally { this.depth--; }
  }

  private modifiers() {
    let required = true, optional = false, immutable = false, indexed = false, unique = false, autoIncrement = false, hidden = false;
    let constraint: Constraint | undefined;
    loop: while (true) {
      switch (this.lex.peek().type) {
        case TokenType.Star: this.lex.next(); required = true; break;
        case TokenType.Question: this.lex.next(); required = false; optional = true; break;
${modCases.split('\n').filter(l => !l.includes('Star') && !l.includes('Question')).join('\n')}
        case TokenType.LParen: constraint = this.constraint(); break;
        default: break loop;
      }
    }
    return { required, optional, immutable, indexed, unique, autoIncrement, hidden, constraint };
  }

  private constraint(): Constraint {
    this.lex.expect(TokenType.LParen);
    let min: number | undefined, max: number | undefined;
    if (this.lex.check(TokenType.Number)) { min = parseFloat(this.lex.next().value); if (Object.is(min, -0)) min = 0; }
    if (this.lex.check(TokenType.Comma)) { this.lex.next(); if (this.lex.check(TokenType.Number)) { max = parseFloat(this.lex.next().value); if (Object.is(max, -0)) max = 0; } } else { max = min; }
    this.lex.expect(TokenType.RParen);
    if (min !== undefined && max !== undefined && min > max) {
      this.diagnostic(new Error(\`Invalid constraint: min (\${min}) > max (\${max})\`));
    }
    const c: Constraint = {};
    if (min !== undefined) c.min = min;
    if (max !== undefined) c.max = max;
    return c;
  }

  private defaultValue(): DefaultValue | undefined {
    if (!this.lex.check(TokenType.Equals)) return undefined;
    this.lex.next();
    const tok = this.lex.next();
    switch (tok.type) {
      case TokenType.String: return tok.value;
      case TokenType.Number: return parseFloat(tok.value);
      case TokenType.Ident:
        if (tok.value === 'true') return true;
        if (tok.value === 'false') return false;
        if (tok.value === 'null') return null;
        return tok.value;
      default: throw this.lex.error(\`Expected default value, got \${TokenType[tok.type]}\`, tok);
    }
  }

  private diagnostic(e: unknown): void {
    const msg = e instanceof Error ? e.message : String(e);
    const tok = this.lex.peek();
    this.diag.push({ message: msg, line: tok.line, column: tok.column, offset: tok.offset });
  }

  private recoverField(): void { while (true) { const t = this.lex.peek().type; if (t === TokenType.Comma || t === TokenType.RBrace || t === TokenType.EOF) return; this.lex.next(); } }

  private recoverEntity(): void {
    let depth = 0;
    while (true) {
      const t = this.lex.peek().type;
      if (t === TokenType.EOF) return;
      if (t === TokenType.LBrace) depth++;
      if (t === TokenType.RBrace) { this.lex.next(); if (depth <= 1) return; depth--; continue; }
      this.lex.next();
    }
  }
}
`;
}

// ── Stream ──

function stream(): string {
  return `/** Generated by Kappa parser generator. Do not edit. */

import { Parser } from './parser.js';
import type { Entity, Field, Diagnostic } from './ast.js';

export type FieldHandler = (field: Field, entityName: string) => void;
export type EntityHandler = (entity: Entity) => void;
export type ErrorHandler = (diagnostic: Diagnostic) => void;

export class StreamingParser {
  private buf = '';
  private entityName: string | null = null;
  private fields: Field[] = [];
  private parenDepth = 0;
  private bracketDepth = 0;
  private inString = false;
  private stringQuote = '';
  private escaped = false;
  private inLineComment = false;
  private prevChar = '';
  private fieldHandlers: FieldHandler[] = [];
  private entityHandlers: EntityHandler[] = [];
  private errorHandlers: ErrorHandler[] = [];

  onField(fn: FieldHandler): this { this.fieldHandlers.push(fn); return this; }
  onEntity(fn: EntityHandler): this { this.entityHandlers.push(fn); return this; }
  onError(fn: ErrorHandler): this { this.errorHandlers.push(fn); return this; }

  feed(ch: string): void {
    if (this.inString) {
      this.buf += ch;
      if (this.escaped) { this.escaped = false; }
      else if (ch === '\\\\') { this.escaped = true; }
      else if (ch === this.stringQuote) { this.inString = false; }
      this.prevChar = ch; return;
    }
    if (ch === '"' || ch === "'") { this.inString = true; this.stringQuote = ch; this.buf += ch; this.prevChar = ch; return; }
    if (this.inLineComment) { if (ch === '\\n') this.inLineComment = false; this.prevChar = ch; return; }
    if (ch === '/' && this.prevChar === '/') { this.buf = this.buf.slice(0, -1); this.inLineComment = true; this.prevChar = ch; return; }

    this.buf += ch;
    if (ch === '(') this.parenDepth++;
    else if (ch === ')') this.parenDepth--;
    else if (ch === '[') this.bracketDepth++;
    else if (ch === ']') this.bracketDepth--;

    if (ch === '{' && this.entityName === null && this.parenDepth === 0) {
      const header = this.buf.slice(0, -1).trim();
      if (header && /^[A-Za-z_]\\w*$/.test(header)) {
        this.entityName = header; this.fields = []; this.buf = '';
      }
      this.prevChar = ch; return;
    }

    if (this.entityName !== null && this.parenDepth === 0 && this.bracketDepth === 0 && (ch === ',' || ch === '}')) {
      const fieldText = this.buf.slice(0, -1).trim();
      if (fieldText) this.emitField(fieldText);
      this.buf = '';
      if (ch === '}') {
        const entity: Entity = { kind: 'entity', name: this.entityName, fields: [...this.fields], uniqueConstraints: [] };
        for (const fn of this.entityHandlers) fn(entity);
        this.entityName = null; this.fields = [];
      }
    }
    this.prevChar = ch;
  }

  write(text: string): void { for (let i = 0; i < text.length; i++) this.feed(text[i]); }

  end(): Field[] {
    const remaining = this.buf.trim();
    if (remaining && this.entityName !== null) this.emitField(remaining);
    return [...this.fields];
  }

  private emitField(text: string): void {
    const input = \`_K { \${text} }\`;
    const parser = new Parser(input);
    const result = parser.parse();
    if (result.diagnostics.length > 0) { for (const d of result.diagnostics) for (const fn of this.errorHandlers) fn(d); return; }
    const ent = result.entities[0];
    if (ent && ent.fields.length > 0) {
      const field = ent.fields[0];
      this.fields.push(field);
      for (const fn of this.fieldHandlers) fn(field, this.entityName!);
    }
  }
}
`;
}

// ── Index ──

function index(): string {
  return `/** Generated by Kappa parser generator. Do not edit. */

export type { TypeCode, PrimitiveType, ArrayType, ReferenceType, EnumType, FieldType, Constraint, DefaultValue, Field, EnumDeclaration, Entity, KappaFile, Diagnostic } from './ast.js';
export { TYPE_CODES } from './ast.js';
export { Parser } from './parser.js';
export type { ParseOptions, FieldCallback, EntityCallback } from './parser.js';
export { StreamingParser } from './stream.js';
export type { FieldHandler, EntityHandler, ErrorHandler } from './stream.js';

import { Parser } from './parser.js';
import type { KappaFile } from './ast.js';

export function parse(input: string): KappaFile {
  return new Parser(input).parse();
}
`;
}
