/** Generate Go parser source files. */

import { tokens, typeCodes, modifiers } from './spec.js';

export function emitGo(): Record<string, string> {
  return {
    'kappa.go': combined(),
    'go.mod': goMod(),
  };
}

function goMod(): string {
  return `module github.com/owenob1/kappa/parsers/go

go 1.21
`;
}

function combined(): string {
  const tokenConsts = tokens.map((t, i) => `\tToken${t.name}${i === 0 ? ' TokenType = iota' : ''}`).join('\n');
  const tokenNames = tokens.map(t => `\tToken${t.name}: "${t.name}",`).join('\n');
  const singleChars = tokens
    .filter(t => t.literal && t.literal.length === 1)
    .map(t => `\tcase '${t.literal}':\n\t\tl.adv()\n\t\treturn l.tok(Token${t.name}, "${t.literal}", start)`)
    .join('\n');
  const typeCodeCases = typeCodes.map(t => `"${t.code}"`).join(', ');
  // Filter out Star and Question — handled explicitly with required-by-default logic
  const modCases = modifiers
    .filter(m => m.token !== 'Star' && m.token !== 'Question')
    .map(m => `\t\tcase Token${m.token}:\n\t\t\tp.lex.next()\n\t\t\tm.${capitalize(m.field)} = true`)
    .join('\n');

  return `// Package kappa provides a parser for Kappa dense notation.
// Generated by Kappa parser generator. Do not edit.
package kappa

import (
\t"fmt"
\t"strconv"
\t"strings"
\t"unicode"
)

// ── Tokens ──

type TokenType int

const (
${tokenConsts}
)

var tokenNames = map[TokenType]string{
${tokenNames}
}

func (t TokenType) String() string { return tokenNames[t] }

type Token struct {
\tType   TokenType
\tValue  string
\tLine   int
\tColumn int
\tOffset int
}

// ── AST ──

type FieldType interface{ fieldType() }

type PrimitiveType struct{ Code string }
type ArrayType struct{ ElementType FieldType }
type ReferenceType struct{ Entity string }
type EnumType struct{ Values []string }

func (PrimitiveType) fieldType() {}
func (ArrayType) fieldType()     {}
func (ReferenceType) fieldType() {}
func (EnumType) fieldType()      {}

type Constraint struct {
\tMin *float64
\tMax *float64
}

type DefaultValue interface{}

type Field struct {
\tName             string
\tType             FieldType
\tRequired         bool
\tOptional         bool
\tImmutable        bool
\tIndexed          bool
\tUnique           bool
\tAutoIncrement    bool
\tHidden           bool
\tFormat           string
\tConstraint       *Constraint
\tDefault          DefaultValue
}

type EnumDeclaration struct {
\tName   string
\tValues []string
}

type Entity struct {
\tName              string
\tFields            []Field
\tUniqueConstraints [][]string
}

type Diagnostic struct {
\tMessage string
\tLine    int
\tColumn  int
\tOffset  int
}

type KappaFile struct {
\tEntities         []Entity
\tEnumDeclarations []EnumDeclaration
\tDiagnostics      []Diagnostic
}

func isTypeCode(s string) bool {
\tswitch s {
\tcase ${typeCodeCases}:
\t\treturn true
\t}
\treturn false
}

// ── Lexer ──

type Lexer struct {
\tsrc    []rune
\tpos    int
\tline   int
\tcol    int
\tpeeked *Token
}

func NewLexer(source string) *Lexer {
\treturn &Lexer{src: []rune(source), pos: 0, line: 1, col: 1}
}

func (l *Lexer) peek() Token {
\tif l.peeked == nil {
\t\tt := l.scan()
\t\tl.peeked = &t
\t}
\treturn *l.peeked
}

func (l *Lexer) next() Token {
\tif l.peeked != nil {
\t\tt := *l.peeked
\t\tl.peeked = nil
\t\treturn t
\t}
\treturn l.scan()
}

func (l *Lexer) check(tt TokenType) bool { return l.peek().Type == tt }

func (l *Lexer) expect(tt TokenType) (Token, error) {
\tt := l.next()
\tif t.Type != tt {
\t\treturn t, fmt.Errorf("expected %s but got %s (%q) at %d:%d", tt, t.Type, t.Value, t.Line, t.Column)
\t}
\treturn t, nil
}

func (l *Lexer) scan() Token {
\tfor {
\t\tl.skipWS()
\t\tif l.pos >= len(l.src) {
\t\t\treturn l.tok(TokenEOF, "", l.pos)
\t\t}
\t\tstart := l.pos
\t\tch := l.src[l.pos]
\t\tswitch ch {
${singleChars}
\t\tcase '+':
\t\t\tif l.at(1) == '+' {
\t\t\t\tl.adv(); l.adv()
\t\t\t\treturn l.tok(TokenPlusPlus, "++", start)
\t\t\t}
\t\tcase '"', '\\'':
\t\t\treturn l.scanStr(start)
\t\tcase '-':
\t\t\tif l.at(1) >= '0' && l.at(1) <= '9' {
\t\t\t\treturn l.scanNum(start)
\t\t\t}
\t\t}
\t\tif ch >= '0' && ch <= '9' {
\t\t\treturn l.scanNum(start)
\t\t}
\t\tif unicode.IsLetter(ch) || ch == '_' {
\t\t\treturn l.scanId(start)
\t\t}
\t\tl.adv() // skip unrecognized character
\t}
}

func (l *Lexer) tok(tt TokenType, value string, offset int) Token {
\tline, col := 1, 1
\tfor i := 0; i < offset && i < len(l.src); i++ {
\t\tif l.src[i] == '\\n' { line++; col = 1 } else { col++ }
\t}
\treturn Token{tt, value, line, col, offset}
}

func (l *Lexer) at(n int) rune {
\ti := l.pos + n
\tif i < len(l.src) { return l.src[i] }
\treturn 0
}

func (l *Lexer) adv() {
\tif l.pos < len(l.src) {
\t\tif l.src[l.pos] == '\\n' { l.line++; l.col = 1 } else { l.col++ }
\t\tl.pos++
\t}
}

func (l *Lexer) skipWS() {
\tfor l.pos < len(l.src) {
\t\tch := l.src[l.pos]
\t\tif ch == ' ' || ch == '\\t' || ch == '\\r' || ch == '\\n' { l.adv(); continue }
\t\tif ch == '/' && l.at(1) == '/' {
\t\t\tl.adv(); l.adv()
\t\t\tfor l.pos < len(l.src) && l.src[l.pos] != '\\n' { l.adv() }
\t\t\tcontinue
\t\t}
\t\tif ch == '/' && l.at(1) == '*' {
\t\t\tl.adv(); l.adv()
\t\t\tfor l.pos < len(l.src) {
\t\t\t\tif l.src[l.pos] == '*' && l.at(1) == '/' { l.adv(); l.adv(); break }
\t\t\t\tl.adv()
\t\t\t}
\t\t\tcontinue
\t\t}
\t\tbreak
\t}
}

func (l *Lexer) scanId(s int) Token {
\tfor l.pos < len(l.src) && (unicode.IsLetter(l.src[l.pos]) || unicode.IsDigit(l.src[l.pos]) || l.src[l.pos] == '_') { l.adv() }
\treturn l.tok(TokenIdent, string(l.src[s:l.pos]), s)
}

func (l *Lexer) scanNum(s int) Token {
\tif l.src[l.pos] == '-' { l.adv() }
\tfor l.pos < len(l.src) && l.src[l.pos] >= '0' && l.src[l.pos] <= '9' { l.adv() }
\tif l.pos < len(l.src) && l.src[l.pos] == '.' && l.at(1) >= '0' && l.at(1) <= '9' {
\t\tl.adv()
\t\tfor l.pos < len(l.src) && l.src[l.pos] >= '0' && l.src[l.pos] <= '9' { l.adv() }
\t}
\treturn l.tok(TokenNumber, string(l.src[s:l.pos]), s)
}

func (l *Lexer) scanStr(s int) Token {
\tq := l.src[l.pos]; l.adv(); cs := l.pos
\tfor l.pos < len(l.src) && l.src[l.pos] != q {
\t\tif l.src[l.pos] == '\\\\' { l.adv(); if l.pos >= len(l.src) { break } }
\t\tl.adv()
\t}
\tv := string(l.src[cs:l.pos])
\tif l.pos < len(l.src) { l.adv() }
\treturn l.tok(TokenString, v, s)
}

// ── Parser ──

const maxDepth = 64
const maxInput = 1_000_000

type Parser struct {
\tlex   *Lexer
\tdiag  []Diagnostic
\tdepth int
}

func NewParser(source string) *Parser {
\treturn &Parser{lex: NewLexer(source)}
}

func Parse(source string) KappaFile {
\tif len(source) > maxInput {
\t\treturn KappaFile{Entities: make([]Entity, 0), EnumDeclarations: make([]EnumDeclaration, 0), Diagnostics: []Diagnostic{{Message: fmt.Sprintf("Input too large: %d bytes (max %d)", len(source), maxInput)}}}
\t}
\treturn NewParser(source).Parse()
}

func (p *Parser) Parse() KappaFile {
\tentities := make([]Entity, 0)
\tenumDeclarations := make([]EnumDeclaration, 0)
\tentityNames := make(map[string]bool)
\tfor {
\t\tif p.lex.check(TokenEOF) { break }
\t\t// Named enum at file level: "enum Name (a|b|c)"
\t\tif p.lex.check(TokenIdent) && p.lex.peek().Value == "enum" {
\t\t\tp.lex.next() // consume "enum"
\t\t\ted, err := p.parseEnumDecl()
\t\t\tif err != nil {
\t\t\t\tp.addDiag(err.Error())
\t\t\t\tp.recoverEntity()
\t\t\t\tcontinue
\t\t\t}
\t\t\tenumDeclarations = append(enumDeclarations, ed)
\t\t\tcontinue
\t\t}
\t\tent, err := p.entity()
\t\tif err != nil {
\t\t\tp.addDiag(err.Error())
\t\t\tp.recoverEntity()
\t\t\tcontinue
\t\t}
\t\tif entityNames[ent.Name] {
\t\t\tp.addDiag(fmt.Sprintf("Duplicate entity name: '%s'", ent.Name))
\t\t}
\t\tentityNames[ent.Name] = true
\t\tentities = append(entities, ent)
\t}
\treturn KappaFile{Entities: entities, EnumDeclarations: enumDeclarations, Diagnostics: p.diag}
}

func (p *Parser) parseEnumDecl() (EnumDeclaration, error) {
\tnameTok, err := p.lex.expect(TokenIdent)
\tif err != nil { return EnumDeclaration{}, err }
\tif _, err := p.lex.expect(TokenLParen); err != nil { return EnumDeclaration{}, err }
\tv, err := p.lex.expect(TokenIdent)
\tif err != nil { return EnumDeclaration{}, err }
\tvalues := []string{v.Value}
\tfor p.lex.check(TokenPipe) {
\t\tp.lex.next()
\t\tv2, err := p.lex.expect(TokenIdent)
\t\tif err != nil { return EnumDeclaration{}, err }
\t\tvalues = append(values, v2.Value)
\t}
\tif _, err := p.lex.expect(TokenRParen); err != nil { return EnumDeclaration{}, err }
\treturn EnumDeclaration{Name: nameTok.Value, Values: values}, nil
}

func (p *Parser) entity() (Entity, error) {
\tnameTok, err := p.lex.expect(TokenIdent)
\tif err != nil { return Entity{}, err }
\tif _, err := p.lex.expect(TokenLBrace); err != nil { return Entity{}, err }
\tfields, err := p.fieldList()
\tif err != nil { return Entity{}, err }
\tif _, err := p.lex.expect(TokenRBrace); err != nil { return Entity{}, err }
\tuniqueConstraints := make([][]string, 0)
\t// @unique(fields) after closing }
\tfor p.lex.check(TokenAt) {
\t\tp.lex.next() // @
\t\tkw, err := p.lex.expect(TokenIdent)
\t\tif err != nil { return Entity{}, err }
\t\tif kw.Value == "unique" || kw.Value == "index" {
\t\t\tif _, err := p.lex.expect(TokenLParen); err != nil { return Entity{}, err }
\t\t\tf, err := p.lex.expect(TokenIdent)
\t\t\tif err != nil { return Entity{}, err }
\t\t\tuc := []string{f.Value}
\t\t\tfor p.lex.check(TokenComma) {
\t\t\t\tp.lex.next()
\t\t\t\tf2, err := p.lex.expect(TokenIdent)
\t\t\t\tif err != nil { return Entity{}, err }
\t\t\t\tuc = append(uc, f2.Value)
\t\t\t}
\t\t\tif _, err := p.lex.expect(TokenRParen); err != nil { return Entity{}, err }
\t\t\tuniqueConstraints = append(uniqueConstraints, uc)
\t\t}
\t}
\treturn Entity{Name: nameTok.Value, Fields: fields, UniqueConstraints: uniqueConstraints}, nil
}

func (p *Parser) fieldList() ([]Field, error) {
\tfields := make([]Field, 0)
\tfieldNames := make(map[string]bool)
\tif p.lex.check(TokenRBrace) { return fields, nil }
\tf, err := p.field(fieldNames)
\tif err != nil {
\t\tp.addDiag(err.Error())
\t\tp.recoverField()
\t} else {
\t\tfields = append(fields, f)
\t}
\tfor p.lex.check(TokenComma) {
\t\tp.lex.next()
\t\tif p.lex.check(TokenRBrace) { break }
\t\tf, err := p.field(fieldNames)
\t\tif err != nil {
\t\t\tp.addDiag(err.Error())
\t\t\tp.recoverField()
\t\t} else {
\t\t\tfields = append(fields, f)
\t\t}
\t}
\treturn fields, nil
}

func (p *Parser) recoverField() {
\tfor {
\t\ttt := p.lex.peek().Type
\t\tif tt == TokenComma || tt == TokenRBrace || tt == TokenEOF { return }
\t\tp.lex.next()
\t}
}

func (p *Parser) field(fieldNames map[string]bool) (Field, error) {
\tnameTok, err := p.lex.expect(TokenIdent)
\tif err != nil { return Field{}, err }
\tif _, err := p.lex.expect(TokenColon); err != nil { return Field{}, err }
\tft, err := p.fieldType()
\tif err != nil { return Field{}, err }
\tm, err := p.modifiers()
\tif err != nil { return Field{}, err }
\t// #format annotation after modifiers
\tif p.lex.check(TokenHash) {
\t\tp.lex.next() // consume #
\t\tfmtTok, err := p.lex.expect(TokenIdent)
\t\tif err != nil { return Field{}, err }
\t\tm.Format = fmtTok.Value
\t}
\tdef, err := p.defaultValue()
\tif err != nil { return Field{}, err }
\t// Semantic validation
\tif m.Required && m.Optional {
\t\tp.addDiag(fmt.Sprintf("Field '%s' has conflicting modifiers '*' and '?'", nameTok.Value))
\t}
\tif fieldNames[nameTok.Value] {
\t\tp.addDiag(fmt.Sprintf("Duplicate field name '%s'", nameTok.Value))
\t}
\tfieldNames[nameTok.Value] = true
\tm.Name = nameTok.Value
\tm.Type = ft
\tm.Default = def
\treturn m, nil
}

func (p *Parser) fieldType() (FieldType, error) {
\tp.depth++
\tif p.depth > maxDepth { p.depth--; return nil, fmt.Errorf("maximum nesting depth exceeded") }
\tdefer func() { p.depth-- }()
\tif p.lex.check(TokenLBracket) {
\t\tp.lex.next()
\t\tel, err := p.fieldType()
\t\tif err != nil { return nil, err }
\t\tif _, err := p.lex.expect(TokenRBracket); err != nil { return nil, err }
\t\treturn ArrayType{ElementType: el}, nil
\t}
\tif p.lex.check(TokenLParen) {
\t\tp.lex.next()
\t\ttok, err := p.lex.expect(TokenIdent)
\t\tif err != nil { return nil, err }
\t\tvalues := []string{tok.Value}
\t\tfor p.lex.check(TokenPipe) {
\t\t\tp.lex.next()
\t\t\tv, err := p.lex.expect(TokenIdent)
\t\t\tif err != nil { return nil, err }
\t\t\tvalues = append(values, v.Value)
\t\t}
\t\tif _, err := p.lex.expect(TokenRParen); err != nil { return nil, err }
\t\treturn EnumType{Values: values}, nil
\t}
\tif p.lex.check(TokenIdent) {
\t\ttok := p.lex.next()
\t\tif isTypeCode(tok.Value) { return PrimitiveType{Code: tok.Value}, nil }
\t\treturn ReferenceType{Entity: tok.Value}, nil
\t}
\ttok := p.lex.peek()
\treturn nil, fmt.Errorf("expected field type, got %s at %d:%d", tok.Type, tok.Line, tok.Column)
}

func (p *Parser) modifiers() (Field, error) {
\tm := Field{Required: true}
\tfor {
\t\tswitch p.lex.peek().Type {
\t\tcase TokenStar:
\t\t\tp.lex.next()
\t\t\tm.Required = true
\t\tcase TokenQuestion:
\t\t\tp.lex.next()
\t\t\tm.Required = false
\t\t\tm.Optional = true
${modCases}
\t\tcase TokenLParen:
\t\t\tc, err := p.constraint()
\t\t\tif err != nil { return m, err }
\t\t\tm.Constraint = &c
\t\tdefault:
\t\t\treturn m, nil
\t\t}
\t}
}

func (p *Parser) constraint() (Constraint, error) {
\tif _, err := p.lex.expect(TokenLParen); err != nil { return Constraint{}, err }
\tvar mn, mx *float64
\tif p.lex.check(TokenNumber) {
\t\tv, _ := strconv.ParseFloat(p.lex.next().Value, 64)
\t\tmn = &v
\t}
\tif p.lex.check(TokenComma) {
\t\tp.lex.next()
\t\tif p.lex.check(TokenNumber) {
\t\t\tv, _ := strconv.ParseFloat(p.lex.next().Value, 64)
\t\t\tmx = &v
\t\t}
\t} else {
\t\tmx = mn
\t}
\tif _, err := p.lex.expect(TokenRParen); err != nil { return Constraint{}, err }
\treturn Constraint{Min: mn, Max: mx}, nil
}

func (p *Parser) defaultValue() (DefaultValue, error) {
\tif !p.lex.check(TokenEquals) { return nil, nil }
\tp.lex.next()
\ttok := p.lex.next()
\tswitch tok.Type {
\tcase TokenString:
\t\treturn tok.Value, nil
\tcase TokenNumber:
\t\tv, _ := strconv.ParseFloat(tok.Value, 64)
\t\treturn v, nil
\tcase TokenIdent:
\t\tswitch tok.Value {
\t\tcase "true": return true, nil
\t\tcase "false": return false, nil
\t\tcase "null": return nil, nil
\t\tdefault: return tok.Value, nil
\t\t}
\t}
\treturn nil, fmt.Errorf("expected default value, got %s at %d:%d", tok.Type, tok.Line, tok.Column)
}

func (p *Parser) addDiag(msg string) {
\ttok := p.lex.peek()
\tp.diag = append(p.diag, Diagnostic{Message: msg, Line: tok.Line, Column: tok.Column, Offset: tok.Offset})
}

func (p *Parser) recoverEntity() {
\tdepth := 0
\tfor {
\t\ttt := p.lex.peek().Type
\t\tif tt == TokenEOF { return }
\t\tif tt == TokenLBrace { depth++ }
\t\tif tt == TokenRBrace { p.lex.next(); if depth <= 1 { return }; depth--; continue }
\t\tp.lex.next()
\t}
}

// suppress unused import warnings
var _ = strings.Contains
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
